#!/usr/bin/env python3
"""Compact the microcode ROM so the FULL 64K memory map fits on the GW2AR-18.

The CPU addresses microcode as {cond(1), stp(4), IR(8)} = 8192 words x 32 bits =
256 Kbit = 15 BSRAM blocks. With a 64K main memory (32 blocks) that is 47 blocks
and the device has 46 -- which is why the first board build had to alias memory
down to 32K.

But the opcode axis is mostly empty: 88 of 256 encodings are defined, and all 168
undefined ones hold *the same* microcode (verified here, not assumed -- this
script refuses to emit anything if that stops being true). So IR can be squeezed
through a 256-entry map into a 7-bit index: 88 real opcodes plus one shared
"undefined" slot. The ROM becomes {cond, stp, idx} = 4096 x 32 = 128 Kbit,
about 8 blocks, and the full 64K memory fits with room to spare.

The CPU is untouched. It still emits {cond, stp, IR}; the board top unpacks that,
maps IR, and repacks -- so the co-sim keeps verifying exactly the same core.

Emits:
  irmap.vh      combinational IR -> idx case (LUT logic, not a BRAM: the lookup
                must resolve within the microcode-fetch phase)
  ucode_c.hex   4096 x 32 compact microcode image
"""
import sys, os, importlib.util, io, contextlib

def load_opc(microdir):
    cwd = os.getcwd()
    try:
        os.chdir(microdir)
        spec = importlib.util.spec_from_file_location("gu", "genucode.py")
        gu = importlib.util.module_from_spec(spec)
        with contextlib.redirect_stdout(io.StringIO()):
            try: spec.loader.exec_module(gu)
            except SystemExit: pass
        return set(gu.OPC.values())
    finally:
        os.chdir(cwd)

def main():
    here  = os.path.dirname(os.path.abspath(__file__))
    micro = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "..", "..", "microcode")
    outvh = os.path.join(here, "irmap.vh")
    outhex= os.path.join(here, "ucode_c.hex")

    roms = []
    for k in range(4):
        with open(os.path.join(micro, "u%d.bin" % k), "rb") as f:
            b = f.read()
        if len(b) != 8192:
            sys.exit("u%d.bin is %d bytes, expected 8192" % (k, len(b)))
        roms.append(b)
    word = lambda ad: roms[0][ad] | roms[1][ad] << 8 | roms[2][ad] << 16 | roms[3][ad] << 24
    column = lambda ir: tuple(word((c << 12) | (s << 8) | ir)
                              for c in range(2) for s in range(16))

    used = sorted(load_opc(micro))
    unused = [ir for ir in range(256) if ir not in set(used)]

    # The whole trick rests on this being true. Check it, do not assume it.
    sigs = {column(ir) for ir in unused}
    if len(sigs) != 1:
        sys.exit("ABORT: the %d undefined opcodes no longer share one microcode "
                 "pattern (%d distinct). Compaction would change behaviour."
                 % (len(unused), len(sigs)))

    idx = {ir: i for i, ir in enumerate(used)}
    undef_idx = len(used)                     # one shared slot for everything else
    if undef_idx >= 128:
        sys.exit("ABORT: %d opcodes needs more than 7 index bits" % (undef_idx + 1))

    with open(outvh, "w") as f:
        f.write("// GENERATED by mk_compact_ucode.py -- do not edit.\n")
        f.write("// IR -> compact microcode index. Combinational on purpose.\n")
        f.write("case (ir)\n")
        for ir in used:
            f.write("  8'h%02x: idx = 7'd%d;\n" % (ir, idx[ir]))
        f.write("  default: idx = 7'd%d;   // all %d undefined opcodes share one slot\n"
                % (undef_idx, len(unused)))
        f.write("endcase\n")

    inv = {v: k for k, v in idx.items()}
    with open(outhex, "w") as f:
        for cond in range(2):
            for stp in range(16):
                for i in range(128):
                    ir = inv.get(i, unused[0])   # unmapped indices = the undefined column
                    f.write("%08x\n" % word((cond << 12) | (stp << 8) | ir))

    # prove the compact image reproduces the original for every reachable address
    comp = [int(l, 16) for l in open(outhex)]
    for cond in range(2):
        for stp in range(16):
            for ir in range(256):
                i = idx.get(ir, undef_idx)
                got = comp[(cond << 11) | (stp << 7) | i]
                exp = word((cond << 12) | (stp << 8) | ir)
                if got != exp:
                    sys.exit("ABORT: mismatch at cond=%d stp=%d IR=%02x" % (cond, stp, ir))

    print("irmap.vh: %d opcodes + 1 shared undefined slot" % len(used))
    print("ucode_c.hex: %d words (was 8192) -- verified identical for all 8192 "
          "original addresses" % len(comp))

if __name__ == "__main__":
    main()
