/* lib_mem.c - GENERATED by generators/gen_memmap.py. Do not edit.
 * The BIOS/FS scratch + graphics-flag + TPA-base addresses commands name.
 * A command writes `//#use mem` instead of hand-#defining these; a
 * memory-map move is then one `python3 generators/gen_memmap.py`. */

//#define TPABASE   0x5900       /* transient program area base (RUNnable programs load here) */
//#define SBUF      0x1D00       /* sector buffer */
//#define FNAME     0x1F4A       /* 12-byte filename (space-padded) — in for both calls */
//#define FSRC      0x1F56       /* FCREATE: source address of the file data (2 bytes) */
//#define FLEN      0x1F58       /* file length in bytes (3 bytes): FCREATE in, FFIND out */
//#define LBA       0x1F47       /* current LBA, byte 0 (bits 7:0) */
//#define LBA1      0x1F48       /* LBA byte 1 (bits 15:8)  — 0 after CFINIT unless set */
//#define LBA2      0x1F49       /* LBA byte 2 (bits 23:16) — 0 after CFINIT unless set */
//#define DIRLBA    0x1F73       /* current directory start LBA, low byte (16-bit: +DIRLBA1) */
//#define DIRLBA1   0x1F80       /* current directory start LBA, high byte (pairs DIRLBA) */
//#define DIRN      0x1F74       /* current directory sector count (1) */
//#define ROSTAT    0x1F5E       /* read-stream state base (ROLBA..ROCNT, 11 bytes) */
//#define ROSDRV    0x1F85       /* read-stream drive (captured by FOPEN, re-asserted by FG_FILL) */
//#define GFXPRES   0x1FA4       /* 1 = GL card fitted (screen is the display); 0 = headless serial console */
//#define GTSUSP    0x1FA7       /* nonzero = glass TTY suspended (a full-screen GL app owns the screen; CONOUT is serial-only) */
//#define GCONEN    0x1FAF       /* 1 = glass TTY console ENABLED (CONOUT mirrors to the GL screen); 0 = off (serial-only, the default -- `screen on` enables it) */
