#!/usr/bin/env python3
"""netlist2v.py -- translate a gen_eagle card netlist into a STRUCTURAL Verilog
module, wiring the tools/gatesim/prims.v primitives together exactly as the
board is drawn. This lets iverilog simulate the AS-DRAWN logic and prove the
decode/control wiring computes what the memory map / microarchitecture expect.

    python3 tools/gatesim/netlist2v.py memory-card > /tmp/mem.v

Bus signals (any net that reaches the J1 edge connector) become module INPUTS;
every other net is an internal wire the testbench can probe by hierarchical
name (e.g. dut.ROM8CE). Parts without a logic primitive (RAM/ROM, bus buffers,
ACIA, connectors, passives) are skipped -- they are loads, not decode drivers --
and reported to stderr so coverage is honest.
"""
import os, sys, re
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "generators"))
import gen_eagle as GE
DEV = GE.DEV

PRIM = {"7430":"dev_7430", "74138":"dev_74138", "HEX14":"dev_HEX14",
        "7410":"dev_7410", "74260":"dev_74260"}
GATES14 = {"74HCT00":"dev_7400","74HC00":"dev_7400", "74HCT08":"dev_7408","74HC08":"dev_7408",
           "74HCT32":"dev_7432","74HC32":"dev_7432", "74HCT86":"dev_7486","74HC86":"dev_7486"}
# devices intentionally not modelled (loads / passives / connectors)
QUIET = {"DIN96C","DIN96","CAP","CAP1","CAPP","RES","LED","HDR3","HDR4","HDR10",
         "SIP9","RNISO8","RNISO8D","LEDARR8","DIP8SW","SW2","XTAL32","COIN",
         "IDE40","DSUB9F","MINIDIN6","JMP2X3","OSC","PICO"}

def san(s):
    s = s.replace("!","n").replace("-","n")
    s = re.sub(r'[^A-Za-z0-9_]', '_', s)
    if s and s[0].isdigit(): s = "P" + s
    return s

def prim_of(dev, val):
    if dev == "GATES14": return GATES14.get(val)
    return PRIM.get(dev)

def gen(card):
    title, parts, nets = GE.CARDS[card]
    pinnet = {}
    for n, mem in nets.items():
        for (r, p) in mem: pinnet[(r, p)] = n
    inp = {n for n, mem in nets.items() if any(r == "J1" for (r, p) in mem)}
    inp |= {"VCC", "GND"}
    mod = san(card)
    o = ["// GENERATED by tools/gatesim/netlist2v.py from gen_eagle CARDS[%r] -- do not edit" % card,
         "`timescale 1ns/1ns",
         "module %s(%s);" % (mod, ", ".join("input " + san(n) for n in sorted(inp)))]
    for n in sorted(set(nets) - inp):
        o.append("  wire %s;" % san(n))
    skipped = []
    for ref, (dev, val) in sorted(parts.items()):
        pm = prim_of(dev, val)
        if not pm:
            if dev not in QUIET: skipped.append("%s(%s %s)" % (ref, dev, val))
            continue
        conns = [".%s(%s)" % (san(pin), san(net))
                 for pin in DEV[dev]["L"] + DEV[dev]["R"]
                 for net in [pinnet.get((ref, pin))] if net]
        o.append("  %s %s(%s);" % (pm, ref, ", ".join(conns)))
    o.append("endmodule")
    return "\n".join(o), skipped, sorted(inp)

if __name__ == "__main__":
    card = sys.argv[1] if len(sys.argv) > 1 else "memory-card"
    src, skipped, inp = gen(card)
    print(src)
    if skipped:
        sys.stderr.write("netlist2v: %s -- %d unmodelled part(s) skipped (loads/buffers): %s\n"
                         % (card, len(skipped), ", ".join(skipped)))
