/* basic.c - P8X BASIC written in C (2026-09-13), the size/speed twin of the
 * hand-assembled basic/p8xbasic.asm. Same language, tokens (the .BAS format),
 * messages, prompts, limits and GL byte streams; the twelve BASIC tests run
 * against either build. TPA build only (RUN /binc/basic.bin under the OS; BYE
 * returns to the shell).
 *
 * Build:  cat basic/glkwtab.c basic/basic.c > basicc.c  (the GL verb tables,
 *         generated by generators/gen_glkw.py)  ->  clib.py -> p8cc.py
 * Layout: code at $5900; the interpreter's big tables are raw memory above the
 * image ($C600 variables, $C700 string work buffers, $C800 string variables,
 * $CA80 program, $E000 rebuild scratch). The asm twin keeps the equivalent
 * tables at its own BASRAM=$8000 base ($8100 variables, $8300 string variables,
 * $8580 program, PBUF $E000 in the TPA build), so the two binaries are both
 * code + small data and the comparison is like for like.
 *
 * Subset notes: int is 16-bit and compares/divides UNSIGNED, so a signed BASIC
 * compare flips the sign bit of both sides first (sgn()); there is no longjmp,
 * so an error sets `err` and every parse level returns through it.
 */
//#use abi
//#use mem     /* FNAME/FSRC/FLEN/GTSUSP from the memory map */
//#define FFIND    0x0118
//#define FCREATE  0x011B
//#define FLOADAT  0x013F
//#define GLDATA   0xFF50
//#define GLSTAT   0xFF51
//#define GLRBR    0xFF52
//#define GLIDR    0xFF54
//#define VARTAB   0xC600
//#define STRACC   0xC700
//#define STRTMP   0xC740
//#define STRARG   0xC780
//#define STRCMPB  0xC7C0
//#define SVARTAB  0xC800
//#define PROG     0xCA80
//#define PBUF     0xE000
//#define APBUF    0xE080
//#define NAMLEN 6
//#define NVARS 32
//#define SLEN 32
//#define SVENT 40
//#define NSVARS 16
//#define GSMAX 3
//#define FSMAX 3
/* tokens */
//#define T_PRINT 0x80
//#define T_LET 0x81
//#define T_IF 0x82
//#define T_THEN 0x83
//#define T_FOR 0x84
//#define T_TO 0x85
//#define T_NEXT 0x86
//#define T_GOTO 0x87
//#define T_GOSUB 0x88
//#define T_RETURN 0x89
//#define T_INPUT 0x8A
//#define T_REM 0x8B
//#define T_END 0x8C
//#define T_RUN 0x8D
//#define T_LIST 0x8E
//#define T_NEW 0x8F
//#define T_ABS 0x90
//#define T_RND 0x91
//#define T_PEEK 0x92
//#define T_POKE 0x93
//#define T_STEP 0x94
//#define T_BYE 0x95
//#define T_HELP 0x96
//#define T_SAVE 0x97
//#define T_LOAD 0x98
//#define T_CHRS 0x99
//#define T_LEFTS 0x9A
//#define T_RIGHTS 0x9B
//#define T_MIDS 0x9C
//#define T_LEN 0x9D
//#define T_ASC 0x9E
//#define T_OPEN 0x9F
//#define T_CLOSE 0xA0
//#define T_OUTPUT 0xA1
//#define T_STRS 0xA2
//#define T_VAL 0xA3
//#define T_EOF 0xA4
//#define T_LINE 0xA5
//#define T_COLOR 0xA6
//#define T_BOX 0xA7
//#define T_FILL 0xA8
//#define T_NOFILL 0xA9
//#define T_CLS 0xAA
//#define T_PIXELW 0xAB
//#define T_CIRCLE 0xAC
//#define T_PIXELR 0xAE
//#define T_GTEXT 0xAF
//#define T_RGB 0xB1
//#define T_IMAGE 0xB2
//#define T_GL 0xB3
//#define T_GLRD 0xFB
/* relation bits */
//#define R_LT 1
//#define R_EQ 2
//#define R_GT 4

/* the main keyword table: [chars][token]... 0 (the GL verbs, glkw[], come first) */
char kwmain[] = {
    'P','R','I','N','T',0x80, 'L','E','T',0x81, 'I','F',0x82, 'T','H','E','N',0x83,
    'F','O','R',0x84, 'T','O',0x85, 'N','E','X','T',0x86, 'G','O','T','O',0x87,
    'G','O','S','U','B',0x88, 'R','E','T','U','R','N',0x89, 'I','N','P','U','T',0x8A,
    'R','E','M',0x8B, 'E','N','D',0x8C, 'R','U','N',0x8D, 'L','I','S','T',0x8E,
    'N','E','W',0x8F, 'A','B','S',0x90, 'R','N','D',0x91, 'P','E','E','K',0x92,
    'P','O','K','E',0x93, 'S','T','E','P',0x94, 'B','Y','E',0x95, 'H','E','L','P',0x96,
    'S','A','V','E',0x97, 'L','O','A','D',0x98, 'C','H','R',36,0x99, 'L','E','F','T',36,0x9A,
    'R','I','G','H','T',36,0x9B, 'M','I','D',36,0x9C, 'L','E','N',0x9D, 'A','S','C',0x9E,
    'O','P','E','N',0x9F, 'C','L','O','S','E',0xA0, 'O','U','T','P','U','T',0xA1,
    'S','T','R',36,0xA2, 'V','A','L',0xA3, 'E','O','F',0xA4, 'L','I','N','E',0xA5,
    'C','O','L','O','R',0xA6, 'N','O','F','I','L','L',0xA9, 'B','O','X',0xA7,
    'F','I','L','L',0xA8, 'C','L','S',0xAA, 'P','I','X','E','L','W',0xAB,
    'C','I','R','C','L','E',0xAC, 'P','I','X','E','L','R',0xAE, 'G','T','E','X','T',0xAF,
    'R','G','B',0xB1, 'I','M','A','G','E',0xB2, 'G','L','R','D',0xFB, 'G','L',0xB3, 0 };
char glwtab[] = { 0xB3,0x00,0x00,0xDF,0x01,0x00,0x00,0x0F,0x01,
                  0xB2,0x00,0x00,0xDF,0x01,0x00,0x00,0x0F,0x01,
                  0x06,0x1F,0x3F,0x1F };
char gttab[] = { 0xB0,0x00,0x00,0x90,0x81,0x00 };
int pow10[] = { 10000, 1000, 100, 10, 1 };

char lbuf[96];              /* the input line */
char nmbuf[6];              /* a parsed name, upcased, space-padded */
int gstk[6];                /* GOSUB frames: line record, text pointer */
int fstk[15];               /* FOR frames: var index, limit, step, line record, text */
char *tp;                   /* the parse cursor */
char *vt;                   /* VARTAB */
char *sacc;                 /* STRACC .. STRCMPB */
char *stmp;
char *sarg;
char *scmpb;
char *svt;                  /* SVARTAB */
char *prog;
char *pbuf;
char *curline;              /* RUN: the current line record */
char *jumpaddr;
char *strsp;                /* STR$ sink */
int err;                    /* an error unwound the statement */
int running;
int endf;
int branchf;
int branchn;
int jumpf;
int gsp;
int fsp;
int varcnt;
int svarcnt;
int fmode;                  /* data file: 0 closed, 1 input, 2 output */
int outfile;                /* PRINT# routing */
int strsink;
int strsn;
int flook;
int flookc;
int seed;
int prmsh;
int relm;
int rel;
int glfst;
int lnum;                   /* the entered line number / the number being printed */

int stmtline();
int stmt();
int eval();
int expr();
int seval(char *dst);
int sterm(char *dst);
int glvsep();
int synerr();

/* ---- console ---- */
int outc(int c) { bios(CONOUT, 0, c); return 0; }
int crlf() { outc(13); outc(10); return 0; }
int outs(char *s) { while (*s) { outc(*s); s = s + 1; } return 0; }
int putch(int c) {
    if (strsink) { *strsp = c; strsp = strsp + 1; strsn = strsn + 1; }
    else if (outfile) bios(FPUTB, 0, c);
    else bios(CONOUT, 0, c);
    return 0;
}
int getline() {
    int n; int c;
    n = 0; c = 0;
    while (c != 13) {
        c = bios(CONIN, 0, 0) & 255;
        if (c == 13) n = n;
        else if (c == 8 || c == 127) {
            if (n) { n = n - 1; outc(8); outc(32); outc(8); }
        } else { outc(c); lbuf[n] = c; n = n + 1; }
    }
    lbuf[n] = 0;
    crlf();
    return 0;
}

/* ---- characters ---- */
int isdig(int c) { return c >= '0' && c <= '9'; }
int upch(int c) { if (c >= 'a' && c <= 'z') return c - 32; return c; }
int isletter(int c) { c = upch(c); return c >= 'A' && c <= 'Z'; }
int isalnum(int c) { return isdig(c) || isletter(c); }
int sgn(int a) { return a ^ 32768; }             /* bias for a signed compare */
int skipsp() { while (*tp == ' ') tp = tp + 1; return 0; }

/* ---- numbers ---- */
int prdecu(int v) {
    int i; int d; int lz;
    lz = 1; i = 0;
    while (i < 5) {
        d = 0;
        while (v >= pow10[i]) { v = v - pow10[i]; d = d + 1; }
        if (d || i == 4 || lz == 0) { putch(d + 48); lz = 0; }
        i = i + 1;
    }
    return 0;
}
int prdec(int v) { if (v & 32768) { putch('-'); v = 0 - v; } return prdecu(v); }
int parsedec() { int v; int c; v = 0; c = *tp; while (c >= '0' && c <= '9') { v = v + v; v = v + (v << 2) + (c - '0'); tp = tp + 1; c = *tp; } return v; }
int hexval(int c) {
    if (isdig(c)) return c - '0';
    c = upch(c);
    if (c >= 'A' && c <= 'F') return c - 55;
    return -1;
}
int parsehex() { int v; int d; v = 0; while (1) { d = hexval(*tp); if (d == -1) return v; v = (v << 4) | d; tp = tp + 1; } }

/* ---- errors: set err; every level returns through it ---- */
int synerr() {
    if (err) return 0;
    err = 1; outfile = 0; strsink = 0;
    if (running) { outs("?SYNTAX ERROR IN "); prdecu(recnum(curline)); crlf(); }
    else outs("?SYNTAX ERROR\r\n");
    return 0;
}
int nodev() { err = 1; outfile = 0; strsink = 0; outs("?No display\r\n"); return 0; }
int expect(int c) { skipsp(); if (*tp != c) return synerr(); tp = tp + 1; return 0; }

/* ---- keywords ---- */
int kwlen;
int kwmatch(char *t, char *s) {          /* a table entry at s? -> token, kwlen */
    int i; int j; int c; int m;
    i = 0;
    while (t[i]) {
        j = 0; m = 1;
        while (m) {
            c = t[i + j] & 255;
            if (c & 128) {                  /* the token: every letter matched */
                if (!isalnum(s[j])) { kwlen = j; return c; }
                m = 0;                      /* a longer identifier (TOTAL, FORK) */
            } else if (s[j] != c) m = 0;
            else j = j + 1;
        }
        while ((t[i] & 128) == 0) i = i + 1;   /* skip to the token byte */
        i = i + 1;
    }
    return 0;
}
int kwat(char *s) { int t; t = kwmatch(glkw, s); if (t) return t; return kwmatch(kwmain, s); }
int crunch() {
    char *r; char *w; int t;
    r = lbuf; w = lbuf;
    while (*r) {
        if (*r == '"') {
            *w = *r; w = w + 1; r = r + 1;
            while (*r && *r != '"') { *w = *r; w = w + 1; r = r + 1; }
            if (*r) { *w = *r; w = w + 1; r = r + 1; }
        } else if (isletter(*r)) {
            t = kwat(r);
            if (t) { *w = t; w = w + 1; r = r + kwlen; }
            else { *w = *r; w = w + 1; r = r + 1; }
        } else { *w = *r; w = w + 1; r = r + 1; }
    }
    *w = 0;
    return 0;
}
int prkw(int tok) {                      /* print the keyword of a token */
    char *t; int i; int c;
    t = glkw;
    while (1) {
        i = 0;
        while (t[i]) {
            c = t[i] & 255;
            while ((c & 128) == 0) { i = i + 1; c = t[i] & 255; }
            if (c == tok) {
                while ((t[i - 1] & 128) == 0 && i > 0) i = i - 1;   /* back to the word start */
                while ((t[i] & 128) == 0) { outc(t[i]); i = i + 1; }
                return 0;
            }
            i = i + 1;
        }
        if (t == kwmain) return 0;
        t = kwmain;
    }
}

/* ---- entry-time structural check ---- */
int cklead() {                           /* may the token at tp start a statement? 1 = REM */
    int c;
    c = *tp & 255;
    if (c == 0) return 0;
    if (c == T_REM) return 1;
    if (c >= GLV0) { if (c < GLV0 + GLVN) return 0; return -1; }
    if (c & 128) {
        if (c == T_THEN || c == T_TO || c == T_STEP || c == T_ABS || c == T_RND || c == T_PEEK ||
            c == T_CHRS || c == T_LEFTS || c == T_RIGHTS || c == T_MIDS || c == T_LEN || c == T_ASC ||
            c == T_STRS || c == T_VAL || c == T_EOF || c == T_PIXELR || c == T_RGB || c == T_FILL ||
            c == T_NOFILL || c == T_OUTPUT || c == 0xAD || c == 0xB0) return -1;
        return 0;
    }
    if (isletter(c)) return 0;
    return -1;
}
int ckbad() { outs("?SYNTAX ERROR\r\n"); return 1; }
int checkline() {                        /* 1 = rejected */
    int dep; int r; int more;
    tp = lbuf; skipsp();
    while (isdig(*tp)) tp = tp + 1;
    while (1) {
        dep = 0; skipsp();
        r = cklead();
        if (r == -1) return ckbad();
        if (r == 1) return 0;
        more = 0;
        while (more == 0) {
            if (*tp == 0) { if (dep) return ckbad(); return 0; }
            if (*tp == '"') {
                tp = tp + 1;
                while (*tp != '"') { if (*tp == 0) return ckbad(); tp = tp + 1; }
            } else if (*tp == '(') dep = dep + 1;
            else if (*tp == ')') { if (dep == 0) return ckbad(); dep = dep - 1; }
            else if (*tp == ':') { if (dep) return ckbad(); more = 1; }
            tp = tp + 1;
        }
    }
}

/* ---- variables: vt entries name[6] value[2] ---- */
int parsename() {                        /* nmbuf <- the identifier at tp; 0 if none */
    int i;
    int c;
    c = *tp;
    if (c >= 'a' && c <= 'z') c = c - 32;
    if (c < 'A' || c > 'Z') return 0;
    i = 0;
    while (i < NAMLEN) { nmbuf[i] = ' '; i = i + 1; }
    i = 0;
    while ((c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z')) {
        if (i < NAMLEN) { nmbuf[i] = c; i = i + 1; }
        tp = tp + 1; c = *tp;
        if (c >= 'a' && c <= 'z') c = c - 32;
    }
    return 1;
}
int nameeq(char *e) { int k; k = 0; while (k < NAMLEN) { if (e[k] != nmbuf[k]) return 0; k = k + 1; } return 1; }
int varfind() {                          /* nmbuf -> index (created if new) */
    int i; int k; char *e;
    i = 0;
    e = vt;
    while (i < varcnt) {
        if (e[0] == nmbuf[0] && e[1] == nmbuf[1] && e[2] == nmbuf[2] &&
            e[3] == nmbuf[3] && e[4] == nmbuf[4] && e[5] == nmbuf[5]) return i;
        i = i + 1; e = e + 8;
    }
    if (varcnt >= NVARS) { synerr(); return 0; }
    k = 0; while (k < NAMLEN) { e[k] = nmbuf[k]; k = k + 1; }
    e[6] = 0; e[7] = 0;
    varcnt = varcnt + 1;
    return i;
}
int varget() { if (!parsename()) return -1; return varfind(); }
int vget(int i) { int *w; w = vt + (i << 3) + 6; return *w; }
int vset(int i, int v) { int *w; w = vt + (i << 3) + 6; *w = v; return 0; }
int svarfind() {
    int i; int k; char *e;
    i = 0;
    e = svt;
    while (i < svarcnt) { if (nameeq(e)) return i; i = i + 1; e = e + SVENT; }
    if (svarcnt >= NSVARS) { synerr(); return 0; }
    k = 0; while (k < NAMLEN) { e[k] = nmbuf[k]; k = k + 1; }
    e[6] = 0;
    svarcnt = svarcnt + 1;
    return i;
}
int svarget() {                          /* NAME$ -> index, -1 if not a string variable */
    if (!parsename()) return -1;
    if (*tp != '$') return -1;
    tp = tp + 1;
    return svarfind();
}
int speek() {                            /* does tp begin a string expression? (tp kept) */
    char *q; int c;
    while (*tp == ' ') tp = tp + 1;
    c = *tp & 255;
    if (c == '"' || c == T_CHRS || c == T_LEFTS || c == T_RIGHTS || c == T_MIDS || c == T_STRS) return 1;
    c = upch(c);
    if (c < 'A' || c > 'Z') return 0;
    q = tp + 1; c = upch(*q);
    while ((c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z')) { q = q + 1; c = upch(*q); }
    return c == '$';
}

/* ---- strings: [len][data] ---- */
int smove(char *src, char *dst) { int n; n = (*src & 255) + 1; while (n) { *dst = *src; dst = dst + 1; src = src + 1; n = n - 1; } return 0; }
int sapp(char *src, char *dst) {         /* append src onto dst, capped at SLEN */
    int n; int m; char *s;
    m = *dst & 255; n = *src & 255; s = src + 1;
    while (n && m < SLEN) { dst[m + 1] = *s; s = s + 1; m = m + 1; n = n - 1; }
    *dst = m;
    return 0;
}
int scpylit(char *dst) {                 /* "..." at tp -> dst */
    int n;
    tp = tp + 1; n = 0;
    while (*tp && *tp != '"') { if (n < SLEN) { dst[n + 1] = *tp; n = n + 1; } tp = tp + 1; }
    if (*tp) tp = tp + 1;
    *dst = n;
    return 0;
}
int sput(char *s) { int n; n = *s & 255; s = s + 1; while (n) { putch(*s); s = s + 1; n = n - 1; } return 0; }
int sarg_(char *dst) {                   /* a literal or a string variable -> dst */
    int i;
    skipsp();
    if (*tp == '"') return scpylit(dst);
    i = svarget(); if (i == -1) return synerr();
    return smove(svt + (i << 5) + (i << 3) + 6, dst);
}
int clampn(int v) { if (v & 32768) return 0; if (v > 255) return SLEN; return v; }
int substr(int si, int sj) {             /* stmp = sarg[si..si+sj) clamped */
    int l; int k;
    l = *sarg & 255;
    if (si >= l) { *stmp = 0; return 0; }
    if (sj > l - si) sj = l - si;
    k = 0; while (k < sj) { stmp[k + 1] = sarg[si + k + 1]; k = k + 1; }
    *stmp = sj;
    return 0;
}
int stmopen() {                          /* '(' string ',' number ; returns the number */
    tp = tp + 1;
    expect('('); if (err) return 0;
    sarg_(sarg); if (err) return 0;
    expect(','); if (err) return 0;
    return expr();
}
int sterm(char *dst) {
    int c; int n; int i; int l;
    skipsp(); c = *tp & 255;
    if (c == '"') return scpylit(dst);
    if (c == T_CHRS) {
        tp = tp + 1; expect('('); n = expr(); expect(')');
        dst[0] = 1; dst[1] = n; return 0;
    }
    if (c == T_STRS) {
        tp = tp + 1; expect('('); n = expr(); expect(')');
        strsp = dst + 1; strsn = 0; strsink = 1; prdec(n); strsink = 0;
        dst[0] = strsn; return 0;
    }
    if (c == T_LEFTS) {
        n = stmopen(); if (err) return 0;
        substr(0, clampn(n)); expect(')'); return smove(stmp, dst);
    }
    if (c == T_RIGHTS) {
        n = stmopen(); if (err) return 0;
        n = clampn(n); l = *sarg & 255;
        if (n >= l) substr(0, n); else substr(l - n, n);
        expect(')'); return smove(stmp, dst);
    }
    if (c == T_MIDS) {
        n = stmopen(); if (err) return 0;
        if (n & 32768) i = 0; else if (n > 255) i = SLEN; else if (n == 0) i = 0; else i = n - 1;
        skipsp();
        if (*tp == ',') { tp = tp + 1; n = clampn(expr()); } else n = SLEN;
        substr(i, n); expect(')'); return smove(stmp, dst);
    }
    i = svarget(); if (i == -1) return synerr();
    return smove(svt + (i << 5) + (i << 3) + 6, dst);
}
int seval(char *dst) {                   /* term { + term } -> dst (via sacc when dst != sacc) */
    *sacc = 0;
    sterm(stmp); if (err) return 0; sapp(stmp, sacc);
    skipsp();
    while (*tp == '+') {
        tp = tp + 1;
        sterm(stmp); if (err) return 0; sapp(stmp, sacc);
        skipsp();
    }
    if (dst != sacc) smove(sacc, dst);
    return 0;
}
int scmp() {                             /* rel = scmpb vs sacc */
    int la; int lb; int n; int k; int a; int b;
    la = *scmpb & 255; lb = *sacc & 255;
    n = la; if (lb < la) n = lb;
    k = 1;
    while (n) {
        a = scmpb[k] & 255; b = sacc[k] & 255;
        if (a < b) { rel = R_LT; return 0; }
        if (a > b) { rel = R_GT; return 0; }
        k = k + 1; n = n - 1;
    }
    if (la == lb) rel = R_EQ; else if (la < lb) rel = R_LT; else rel = R_GT;
    return 0;
}

/* ---- expressions ---- */
int relopp() {                           /* an operator at tp -> relm (0 if none) */
    while (*tp == ' ') tp = tp + 1;
    if (*tp == '=') { tp = tp + 1; relm = R_EQ; return 1; }
    if (*tp == '<') {
        tp = tp + 1;
        if (*tp == '=') { tp = tp + 1; relm = R_LT + R_EQ; return 1; }
        if (*tp == '>') { tp = tp + 1; relm = R_LT + R_GT; return 1; }
        relm = R_LT; return 1;
    }
    if (*tp == '>') {
        tp = tp + 1;
        if (*tp == '=') { tp = tp + 1; relm = R_GT + R_EQ; return 1; }
        relm = R_GT; return 1;
    }
    return 0;
}
int parget() { int v; expect('('); if (err) return 0; v = expr(); expect(')'); return v; }
int random_() { seed = seed * 25173 + 13849; return seed; }
int glrdw() { while ((peek(GLSTAT) & 1) == 0) ; return peek(GLRBR); }
int glput(int c) { while (peek(GLSTAT) & 128) ; poke(GLDATA, c); return 0; }
int glpw(int v) { glput(v); glput(v >> 8); return 0; }
int gcheck() { if (peek(GLIDR) != 'G') { nodev(); return 0; } return 1; }
int rgbtail(int r) {                     /* r ; ",g,b" -> packed 565 */
    int g; int b;
    expect(','); if (err) return 0;
    g = expr() & 63;
    expect(','); if (err) return 0;
    b = expr() & 31;
    return ((r & 31) << 11) | (g << 5) | b;
}
int factor() {
    int c; int v; int i; char *save; int neg;
    while (*tp == ' ') tp = tp + 1; c = *tp & 255;
    if (c == '-') { tp = tp + 1; return 0 - factor(); }
    if (c == '+') { tp = tp + 1; return factor(); }
    if (c == '(') { tp = tp + 1; v = expr(); expect(')'); return v; }
    if (c == T_GLRD) { tp = tp + 1; if ((peek(GLSTAT) & 1) == 0) return -1; return peek(GLRBR); }
    if (c == T_ABS) { tp = tp + 1; v = parget(); if (v & 32768) return 0 - v; return v; }
    if (c == T_PEEK) { tp = tp + 1; return peek(parget()); }
    if (c == T_RND) {
        tp = tp + 1; v = parget();
        if (v == 0) return 0;
        return (random_() % v) + 1;
    }
    if (c == T_LEN) { tp = tp + 1; expect('('); sarg_(sarg); expect(')'); return *sarg & 255; }
    if (c == T_ASC) { tp = tp + 1; expect('('); sarg_(sarg); expect(')'); if (*sarg == 0) return 0; return sarg[1] & 255; }
    if (c == T_VAL) {
        tp = tp + 1; expect('('); sarg_(sarg); expect(')'); if (err) return 0;
        sarg[(*sarg & 255) + 1] = 0;
        save = tp; tp = sarg + 1; skipsp(); neg = 0;
        if (*tp == '-') { neg = 1; tp = tp + 1; } else if (*tp == '+') tp = tp + 1;
        v = parsedec(); tp = save;
        if (neg) return 0 - v;
        return v;
    }
    if (c == T_EOF) { tp = tp + 1; parget(); if (fmode != 1) return 1; return flookc; }
    if (c == T_PIXELR) {
        tp = tp + 1;
        if (!gcheck()) return 0;
        expect('('); if (err) return 0;
        glput(0x63); glpw(expr());
        expect(','); if (err) return 0;
        glpw(expr()); expect(')');
        v = glrdw(); return v | (glrdw() << 8);
    }
    if (c == T_RGB) { tp = tp + 1; expect('('); if (err) return 0; v = rgbtail(expr()); expect(')'); return v; }
    if (c >= '0' && c <= '9') {
        if (c == '0' && (tp[1] == 'x' || tp[1] == 'X')) { tp = tp + 2; return parsehex(); }
        return parsedec();
    }
    if (c & 128) { synerr(); return 0; }
    i = varget();
    if (i == -1) { synerr(); return 0; }
    return vget(i);
}
int term() {
    int v; int c; int r;
    v = factor();
    while (1) {
        while (*tp == ' ') tp = tp + 1; c = *tp;
        if (c == '*') { tp = tp + 1; v = v * factor(); }
        else if (c == '/') { tp = tp + 1; r = factor(); if (r == 0) v = 0; else v = v / r; }
        else if (c == '%') { tp = tp + 1; r = factor(); if (r == 0) v = 0; else v = v % r; }
        else return v;
        if (err) return 0;
    }
}
int expr() {
    int v; int c;
    v = term();
    while (1) {
        while (*tp == ' ') tp = tp + 1; c = *tp;
        if (c == '+') { tp = tp + 1; v = v + term(); }
        else if (c == '-') { tp = tp + 1; v = v - term(); }
        else return v;
        if (err) return 0;
    }
}
int relresult() { if (rel & relm) return 1; return 0; }
int evalstr() {                          /* a string comparison -> 1/0 */
    seval(scmpb); if (err) return 0;
    if (!relopp()) { synerr(); return 0; }
    seval(sacc); if (err) return 0;
    scmp();
    return relresult();
}
int eval() {                             /* expr [relop expr] -> value / 1 / 0 */
    int l; int r;
    if (speek()) return evalstr();
    l = expr(); if (err) return 0;
    if (!relopp()) return l;
    r = expr(); if (err) return 0;
    if (sgn(l) < sgn(r)) rel = R_LT; else if (l == r) rel = R_EQ; else rel = R_GT;
    return relresult();
}

/* ---- program text ---- */
int recnum(char *p) { int *w; w = p; return *w; }
int setrec(char *p, int n) { int *w; w = p; *w = n; return 0; }
char *nextrec(char *p) { p = p + 2; while (*p) p = p + 1; return p + 1; }
int newprog() { prog[0] = 0; prog[1] = 0; varcnt = 0; svarcnt = 0; return 0; }
char *findline(int n) {                  /* the record numbered n, 0 if none */
    char *p; int r;
    p = prog;
    while (1) {
        r = recnum(p);
        if (r == 0 || r > n) return 0;
        if (r == n) return p;
        p = nextrec(p);
    }
}
int cpytext(char *s, char *d) { while (*s) { *d = *s; d = d + 1; s = s + 1; } *d = 0; return 0; }
int edit(char *text) {                   /* insert / replace / delete line lnum */
    char *s; char *d; int r; int ins; int del;
    del = (*text == 0); ins = 0;
    s = prog; d = pbuf;
    r = recnum(s);
    while (r) {
        if (ins == 0 && r >= lnum) {
            if (!del) { setrec(d, lnum); cpytext(text, d + 2); d = nextrec(d); }
            ins = 1;
        }
        if (r == lnum) s = nextrec(s);       /* the old line is dropped */
        else {
            setrec(d, r); cpytext(s + 2, d + 2);
            d = nextrec(d); s = nextrec(s);
        }
        r = recnum(s);
    }
    if (ins == 0 && !del) { setrec(d, lnum); cpytext(text, d + 2); d = nextrec(d); }
    d[0] = 0; d[1] = 0;
    s = pbuf; d = prog;                   /* copy back */
    while (1) {
        r = recnum(s);
        setrec(d, r);
        if (r == 0) return 0;
        cpytext(s + 2, d + 2);
        s = nextrec(s); d = nextrec(d);
    }
}
int prtext(char *p) { int c; while (*p) { c = *p & 255; if (c & 128) prkw(c); else outc(c); p = p + 1; } return 0; }
int list() {
    char *p; int r;
    p = prog;
    while (1) {
        r = recnum(p);
        if (r == 0) return 0;
        prdecu(r); outc(' '); prtext(p + 2); crlf();
        p = nextrec(p);
    }
}
int proglen() { char *p; p = prog; while (recnum(p)) p = nextrec(p); return p + 2 - prog; }

/* ---- files ---- */
char *apath(char *p) {                   /* absolute path (CWD-prefixed) -> APBUF or p */
    char *a;
    if (*p == '/') return p;
    a = APBUF;
    bios(SYS_GETCWD, a, 0);
    while (*a) a = a + 1;
    if (a[-1] != '/') { *a = '/'; a = a + 1; }
    while (*p) { *a = *p; a = a + 1; p = p + 1; }
    *a = 0;
    return APBUF;
}
int getpath() {                          /* "path" at tp -> PBUF (NUL-terminated); 1 = ok */
    char *d; int n;
    skipsp();
    if (*tp != '"') return 0;
    tp = tp + 1; d = pbuf; n = 0;
    while (*tp && *tp != '"') { if (n < 47) { *d = *tp; d = d + 1; n = n + 1; } tp = tp + 1; }
    if (*tp) tp = tp + 1;
    *d = 0;
    return 1;
}
int setfname() {                         /* name$ -> resolved dir + FNAME */
    char *s;
    seval(sacc); if (err) return 0;
    s = sacc + 1; s[*sacc & 255] = 0;
    bios(FRESOLVE, apath(s), 0);
    return 0;
}
int fprime() { int c; c = bios(FGETB, 0, 0); if (c & 256) flookc = 1; else { flookc = 0; flook = c & 255; } return 0; }
int gnb() {                              /* the next input byte via the lookahead, -1 at EOF */
    int c;
    if (flookc) return -1;
    c = flook;
    fprime();
    return c;
}
int freadrec() {                         /* one CR-delimited record -> sacc, NUL-terminated */
    int n; int c;
    n = 0; c = 0;
    while (c != -1 && c != 13) {
        c = gnb();
        if (c != -1 && c != 13 && n < SLEN) { sacc[n + 1] = c; n = n + 1; }
    }
    sacc[n + 1] = 0; *sacc = n;
    return 0;
}

/* ---- statements ---- */
int st_print() {
    int v;
    tp = tp + 1; skipsp();
    if (*tp == '#') {
        if (fmode != 2) return synerr();
        tp = tp + 1; outfile = 1; skipsp();
        if (*tp) {
            if (speek()) { seval(sacc); if (err) return 0; sput(sacc); }
            else { v = eval(); if (err) return 0; prdec(v); }
        }
        bios(FPUTB, 0, 13); outfile = 0;
        return 0;
    }
    while (1) {
        skipsp();
        if (*tp == 0 || *tp == ':') return crlf();
        if (speek()) { seval(sacc); if (err) return 0; sput(sacc); }
        else { v = eval(); if (err) return 0; prdec(v); }
        skipsp();
        if (*tp == ';') tp = tp + 1;
        else if (*tp == ',') { tp = tp + 1; outc(' '); }
        else return crlf();
        skipsp();
        if (*tp == 0 || *tp == ':') return 0;
    }
}
int st_let() {
    int i; int v;
    if ((*tp & 255) == T_LET) { tp = tp + 1; skipsp(); }
    if (speek()) {
        i = svarget(); if (i == -1) return synerr();
        expect('='); if (err) return 0;
        seval(sacc); if (err) return 0;
        return smove(sacc, svt + (i << 5) + (i << 3) + 6);
    }
    i = varget(); if (i == -1) return synerr();
    expect('='); if (err) return 0;
    v = eval(); if (err) return 0;
    return vset(i, v);
}
int st_gotoN() { branchn = parsedec(); branchf = 1; return 0; }
int st_if() {
    int v;
    tp = tp + 1;
    v = eval(); if (err) return 0;
    skipsp();
    if ((*tp & 255) != T_THEN) return synerr();
    tp = tp + 1;
    if (v == 0) { while (*tp) tp = tp + 1; return 0; }
    skipsp();
    if (isdig(*tp)) return st_gotoN();
    return stmtline();
}
int st_input() {
    int i; char *save; int n;
    tp = tp + 1; skipsp();
    if (*tp == '#') {
        if (fmode != 1) return synerr();
        tp = tp + 1; skipsp();
        if (speek()) {
            i = svarget(); if (i == -1) return synerr();
            save = tp; freadrec(); tp = save;
            return smove(sacc, svt + (i << 5) + (i << 3) + 6);
        }
        i = varget(); if (i == -1) return synerr();
        save = tp; freadrec(); tp = sacc + 1; skipsp(); n = parsedec(); tp = save;
        return vset(i, n);
    }
    if (speek()) {
        i = svarget(); if (i == -1) return synerr();
        save = tp; outc('?'); outc(' '); getline();
        n = 0; while (lbuf[n] && n < SLEN) { sacc[n + 1] = lbuf[n]; n = n + 1; }
        *sacc = n; tp = save;
        return smove(sacc, svt + (i << 5) + (i << 3) + 6);
    }
    i = varget(); if (i == -1) return synerr();
    save = tp; outc('?'); outc(' '); getline();
    tp = lbuf; skipsp(); n = parsedec(); tp = save;
    return vset(i, n);
}
int st_poke() { int a; tp = tp + 1; a = eval(); expect(','); if (err) return 0; poke(a, eval()); return 0; }
int st_gosub() {
    tp = tp + 1; skipsp(); st_gotoN(); skipsp();
    if (*tp == ':') tp = tp + 1;
    if (gsp >= GSMAX) return synerr();
    gstk[gsp + gsp] = curline; gstk[gsp + gsp + 1] = tp;
    gsp = gsp + 1;
    return 0;
}
int st_return() {
    tp = tp + 1;
    if (gsp == 0) { outs("?RETURN WITHOUT GOSUB\r\n"); endf = 1; return 0; }
    gsp = gsp - 1;
    curline = gstk[gsp + gsp]; jumpaddr = gstk[gsp + gsp + 1]; jumpf = 2;
    return 0;
}
int st_for() {
    int i; int v; int lim; int step; char *lr; char *tpp; int *f;
    tp = tp + 1; skipsp();
    i = varget(); if (i == -1) return synerr();
    expect('='); if (err) return 0;
    v = eval(); if (err) return 0;
    vset(i, v);
    skipsp();
    if ((*tp & 255) != T_TO) return synerr();
    tp = tp + 1;
    lim = eval(); if (err) return 0;
    step = 1; skipsp();
    if ((*tp & 255) == T_STEP) { tp = tp + 1; step = eval(); if (err) return 0; }
    skipsp();
    if (*tp == ':') { lr = curline; tpp = tp + 1; }
    else { lr = nextrec(curline); tpp = lr + 2; }
    if (fsp >= FSMAX) return synerr();
    f = fstk + (fsp << 2) + fsp;
    f[0] = i; f[1] = lim; f[2] = step; f[3] = lr; f[4] = tpp;
    fsp = fsp + 1;
    return 0;
}
int st_next() {
    int *f; int v; int fin;
    tp = tp + 1; skipsp();
    if (isletter(*tp)) varget();
    if (fsp == 0) return synerr();
    f = fstk + ((fsp - 1) << 2) + (fsp - 1);
    v = vget(f[0]) + f[2]; vset(f[0], v);
    if (v == f[1]) fin = 0;
    else if (sgn(v) < sgn(f[1])) fin = (f[2] & 32768);     /* below: a DOWN loop is done */
    else fin = ((f[2] & 32768) == 0);                       /* above: an UP loop is done */
    if (fin) { fsp = fsp - 1; return 0; }
    curline = f[3]; jumpaddr = f[4]; jumpf = 2;
    return 0;
}
int st_run() {
    char *p; int go; int inner;
    tp = tp + 1;
    gsp = 0; fsp = 0; fmode = 0; outfile = 0; running = 1;
    curline = prog; go = 1;
    while (go) {
        if (recnum(curline) == 0) go = 0;
        else {
            tp = curline + 2; inner = 1;
            while (inner) {
                branchf = 0; jumpf = 0; endf = 0;
                stmtline();
                if (err || endf) { go = 0; inner = 0; }
                else if (jumpf == 2) tp = jumpaddr;
                else {
                    if (branchf) {
                        p = findline(branchn);
                        if (p == 0) { outs("?UNDEF'D LINE\r\n"); go = 0; }
                        else curline = p;
                    } else curline = nextrec(curline);
                    inner = 0;
                }
            }
        }
    }
    endf = 1;
    if (!err) outs("Ok\r\n");
    return 0;
}
int st_save() {
    tp = tp + 1;
    if (!getpath()) return synerr();
    if (bios(FRESOLVE, apath(pbuf), 0) & 256) { outs("?Save failed\r\n"); return 0; }
    poke(FLEN, proglen()); poke(FLEN + 1, proglen() >> 8); poke(FLEN + 2, 0);
    poke(FSRC, PROG & 255); poke(FSRC + 1, PROG >> 8);
    if (bios(FCREATE, 0, 0) & 256) { outs("?Save failed\r\n"); return 0; }
    outs("Saved\r\n");
    return 0;
}
int st_load() {
    tp = tp + 1;
    if (!getpath()) return synerr();
    if (bios(FRESOLVE, apath(pbuf), 0) & 256) { outs("?No file\r\n"); return 0; }
    if (bios(FFIND, 0, 0) & 256) { outs("?No file\r\n"); return 0; }
    bios(FLOADAT, prog, 0);
    outs("Loaded\r\n");
    return 0;
}
int st_open() {
    int c;
    tp = tp + 1;
    setfname(); if (err) return 0;
    skipsp();
    if ((*tp & 255) == T_FOR) { tp = tp + 1; skipsp(); }
    c = *tp & 255;
    if (c == T_OUTPUT) { tp = tp + 1; bios(FWOPEN, 0, 0); fmode = 2; return 0; }
    if (c != T_INPUT) return synerr();
    tp = tp + 1;
    if (bios(FOPEN, PBUF, 0) & 256) { fmode = 0; outs("?No file\r\n"); return 0; }
    fmode = 1;
    return fprime();
}
int st_close() { tp = tp + 1; if (fmode == 2) bios(FCLOSE, 0, 0); fmode = 0; return 0; }

/* ---- graphics ---- */
int glwin() { int i; i = 0; while (i < 22) { glput(glwtab[i]); i = i + 1; } return 0; }
int glchk() { if (!gcheck()) return 0; glfst = 1; return 1; }
int glvsep() {                           /* comma rule + expression */
    if (glfst) { glfst = 0; return eval(); }
    expect(','); if (err) return 0;
    return eval();
}
int gldrain() { while (peek(GLSTAT) & 64) ; return 0; }
int glsend(char *s) { int n; n = *s & 255; s = s + 1; while (n) { glput(*s); s = s + 1; n = n - 1; } return 0; }
int fillkw() {                           /* ,FILL / ,NOFILL at tp: 0/1, -1 if not present */
    int c;
    skipsp();
    if (*tp != ',') return 0;
    tp = tp + 1; skipsp(); c = *tp & 255;
    if (c == T_FILL) { tp = tp + 1; return 1; }
    if (c == T_NOFILL) { tp = tp + 1; return 0; }
    synerr(); return 0;
}
int prmfil(int f) { glput(0xE0); glput(f); return 0; }
int st_gline() {
    tp = tp + 1; if (!glchk()) return 0;
    glput(0x10); glpw(glvsep()); glpw(glvsep());
    glput(0x28); glpw(glvsep()); glpw(glvsep());
    if (err) return 0;
    return gldrain();
}
int st_color() {
    int v;
    tp = tp + 1; if (!gcheck()) return 0;
    v = eval(); if (err) return 0;
    skipsp();
    if (*tp == ',') { v = rgbtail(v); if (err) return 0; }
    if (peek(GLIDR) != 'G') return 0;
    glput(6); glput(v >> 11); glput((v >> 5) & 63); glput(v & 31);
    return 0;
}
int st_box() {
    int x0; int y0; int x1; int y1; int f;
    tp = tp + 1; if (!glchk()) return 0;
    x0 = glvsep(); y0 = glvsep(); x1 = glvsep(); y1 = glvsep(); if (err) return 0;
    f = fillkw(); if (err) return 0;
    prmfil(f); glput(0x10); glpw(x0); glpw(y0); glput(0x34); glpw(x1); glpw(y1);
    prmfil(prmsh);
    return gldrain();
}
int st_cls() { tp = tp + 1; if (!glchk()) return 0; glput(7); glput(0); glput(0); glput(0); return gldrain(); }
int st_pixw() { tp = tp + 1; if (!glchk()) return 0; glput(0x10); glpw(glvsep()); glpw(glvsep()); if (err) return 0; glput(8); return gldrain(); }
int st_circle() {
    int x; int y; int rx; int ry; int f; int c;
    tp = tp + 1; if (!glchk()) return 0;
    x = glvsep(); y = glvsep(); rx = glvsep(); if (err) return 0;
    ry = rx; f = 0; skipsp();
    if (*tp == ',') {
        tp = tp + 1; skipsp(); c = *tp & 255;
        if (c == T_FILL) { tp = tp + 1; f = 1; }
        else if (c == T_NOFILL) tp = tp + 1;
        else { ry = eval(); if (err) return 0; f = fillkw(); if (err) return 0; }
    }
    prmfil(f); glput(0x10); glpw(x); glpw(y); glput(0x39); glpw(rx); glpw(ry);
    prmfil(prmsh);
    return gldrain();
}
int st_gtext() {
    int x; int y; int s; int i;
    tp = tp + 1; if (!glchk()) return 0;
    x = glvsep(); y = glvsep(); s = glvsep(); if (err) return 0;
    if (s == 0) s = 1;
    expect(','); if (err) return 0;
    i = 0; while (i < 6) { glput(gttab[i]); i = i + 1; }
    glput(s);
    glput(0x96); glpw(x); glpw(y); glput(0); glput(0);
    glput(0x12); i = 0; while (i < 6) { glput(0); i = i + 1; }
    glput(0x80);
    seval(sacc); if (err) return 0;
    glput(*sacc); glsend(sacc);
    return gldrain();
}
int st_gl() {
    tp = tp + 1; if (!gcheck()) return 0;
    seval(sacc); if (err) return 0;
    glput('C'); glput('A'); glput(' ');
    glsend(sacc);
    glput(13); glput('C'); glput('X'); glput(' ');
    return 0;
}
int st_glv(int idx) {                    /* a native GL verb statement */
    int op; int meta; int n; int dim; int v;
    tp = tp + 1; if (!gcheck()) return 0;
    op = glvtab[idx + idx] & 255; meta = glvtab[idx + idx + 1] & 255;
    glput(op);
    if (op == 4) { prmsh = 0; glwin(); }             /* RESETF */
    if (meta == 255) {                                /* TEXT s$ */
        seval(sacc); if (err) return 0;
        glput(*sacc); glsend(sacc);
        return gldrain();
    }
    glfst = 1;
    if (meta & 128) {                                 /* POLY*: count, then vertices */
        n = glvsep(); glput(n);
        dim = 2; if (op & 2) dim = 3;
        while (n) { v = dim; while (v) { glpw(glvsep()); if (err) return 0; v = v - 1; } n = n - 1; }
        return gldrain();
    }
    n = meta >> 4;
    while (n) { v = glvsep(); if (err) return 0; if (op == 0xE0) prmsh = v; glput(v); n = n - 1; }
    n = meta & 15;
    while (n) { glpw(glvsep()); if (err) return 0; n = n - 1; }
    return gldrain();
}
int imgb() { int c; c = bios(FGETB, 0, 0); if (c & 256) return -1; return c & 255; }
int st_image() {
    int x; int y; int w; int h; int n; int c; char *save;
    tp = tp + 1; if (!gcheck()) return 0;
    x = eval(); expect(','); y = eval(); expect(','); if (err) return 0;
    setfname(); if (err) return 0;
    save = tp;
    if (bios(FOPEN, PBUF, 0) & 256) { fmode = 0; outs("?No file\r\n"); tp = save; return 0; }
    fmode = 0;
    if (imgb() != 'P' || imgb() != '8' || imgb() != 'I' || imgb() != 1) { outs("?NOT P8I\r\n"); tp = save; return 0; }
    w = imgb(); w = w | (imgb() << 8);
    h = imgb(); h = h | (imgb() << 8);
    if (imgb() != 16) { outs("?NOT P8I\r\n"); tp = save; return 0; }
    imgb();
    tp = save;
    if (w == 0 || h == 0) return 0;
    y = y + h - 1;
    while (h) {
        glput(0x64); glpw(x); glpw(y); glpw(w); glpw(1);
        n = w + w;
        while (n) {
            c = imgb();
            if (c == -1) { while (n) { glput(0); n = n - 1; } outs("?NOT P8I\r\n"); return 0; }
            glput(c); n = n - 1;
        }
        y = y - 1; h = h - 1;
    }
    return 0;
}

int stmt() {
    int c; int save;
    skipsp(); c = *tp & 255;
    if (c == 0) return 0;
    if (c == T_LET || isletter(c)) return st_let();
    if (c == T_PRINT) return st_print();
    if (c == T_IF) return st_if();
    if (c == T_FOR) return st_for();
    if (c == T_NEXT) return st_next();
    if (c == T_GOTO) { tp = tp + 1; skipsp(); return st_gotoN(); }
    if (c == T_GOSUB) return st_gosub();
    if (c == T_RETURN) return st_return();
    if (c == T_REM) { while (*tp) tp = tp + 1; return 0; }
    if (c == T_END) { tp = tp + 1; endf = 1; return 0; }
    if (c == T_INPUT) return st_input();
    if (c == T_POKE) return st_poke();
    if (c >= GLV0 && c < GLV0 + GLVN) return st_glv(c - GLV0);
    if (c == T_LINE) return st_gline();
    if (c == T_COLOR) return st_color();
    if (c == T_BOX) return st_box();
    if (c == T_CLS) return st_cls();
    if (c == T_PIXELW) return st_pixw();
    if (c == T_CIRCLE) return st_circle();
    if (c == T_GTEXT) return st_gtext();
    if (c == T_GL) return st_gl();
    if (c == T_IMAGE) return st_image();
    if (c == T_RUN) return st_run();
    if (c == T_LIST) { tp = tp + 1; list(); outs("Ok\r\n"); return 0; }
    if (c == T_NEW) { tp = tp + 1; newprog(); outs("Ok\r\n"); return 0; }
    if (c == T_HELP) { tp = tp + 1; outs("\r\nSTATEMENTS: PRINT LET IF/THEN FOR/TO/STEP NEXT\r\n  GOTO GOSUB RETURN INPUT POKE REM END\r\nFILES: OPEN name OUTPUT|INPUT : PRINT# : INPUT# : CLOSE : EOF(n)\r\nCOMMANDS: RUN LIST NEW SAVE LOAD HELP BYE\r\nFUNCTIONS: ABS(x) RND(n) PEEK(a)\r\n  LEN ASC CHR$ LEFT$ RIGHT$ MID$ STR$ VAL\r\nGRAPHICS (window coords, y UP 0-271): COLOR r,g,b : CLS\r\n  LINE x0,y0,x1,y1   BOX x0,y0,x1,y1[,FILL|,NOFILL]\r\n  CIRCLE x,y,r[,ry][,FILL]  PIXELW x,y  PIXELR(x,y)  RGB(r,g,b)\r\n  GTEXT x,y,size,s$  easy 2D text (window coords, absolute size)\r\n  raw: MOVE3 x,y,0 then TEXT s$ (TSIZE COMPOUNDS, MDIDEN resets)\r\n  IMAGE x,y,f$   draw a P8I file, bottom-left at x,y\r\n  + the PGC verbs native: MOVE DRAW POLY RECT AREA TEXT\r\n    LINPAT p (dash bits)  LINFUN m (0=set 1=compl 2=OR 3=AND 4=XOR)\r\n    and the rest - man basic / man gl\r\n  SCREEN IS 480x272 RGB565 - COLOR r,g,b (0-31,0-63,0-31)\r\n  or COLOR c, one PACKED value - from RGB() or PIXELR()\r\nSTRINGS: A$ B$ (assign, + concat, compare)\r\nOPERATORS: + - * / %  = <> < > <= >=\r\n"); return 0; }
    if (c == T_SAVE) return st_save();
    if (c == T_LOAD) return st_load();
    if (c == T_OPEN) return st_open();
    if (c == T_CLOSE) return st_close();
    if (c == T_BYE) { endf = 2; return 0; }
    outs("?\r\n");
    return 0;
}
int stmtline() {
    while (1) {
        stmt();
        if (err || endf || branchf || jumpf) return 0;
        skipsp();
        if (*tp == 0) return 0;
        if (*tp != ':') return synerr();
        tp = tp + 1;
    }
}

int main() {
    char *text;
    vt = VARTAB; sacc = STRACC; stmp = STRTMP; sarg = STRARG; scmpb = STRCMPB;
    svt = SVARTAB; prog = PROG; pbuf = PBUF;
    newprog();
    fmode = 0; outfile = 0; strsink = 0; prmsh = 0; seed = 44257;
    if (peek(GLIDR) == 'G') {
        glwin();                                    /* GL window for graphics; the
                                                       console overlay STAYS on, so
                                                       PRINT shows on the panel over
                                                       BASIC's graphics (two planes) */
        glput(0xB0); glput(0); glput(0);            /* PROJCT 0 */
    }
    outs("\r\nP8X BASIC V0\r\n");
    while (1) {
        running = 0; err = 0; endf = 0; branchf = 0; jumpf = 0;
        getline(); crunch();
        if (checkline() == 0) {
            tp = lbuf; skipsp();
            if (isdig(*tp)) {
                lnum = parsedec(); skipsp(); text = tp;
                edit(text);
            } else if (*tp) {
                stmtline();
                if (endf == 2) return 0;               /* BYE */
            }
        }
    }
}
