/* glkwtab.c - GENERATED by generators/gen_glkw.py. Do not edit.
 * The GL verbs as BASIC keywords: glkw[] is [chars][token]... 0, listed
 * LONGEST-FIRST (tokens $B4 up in BASIC_VERBS order, the .BAS ABI);
 * glvtab[] is two bytes per verb in token order: GL opcode, meta. */
//#define GLV0 180
//#define GLVN 66
char glkw[] = {
    'P','G','S','Y','N','C', 0xB5,
    'R','E','S','E','T','F', 0xB6,
    'P','O','I','N','T','3', 0xB9,
    'C','L','E','A','R','S', 0xBA,
    'M','O','V','E','R','3', 0xBE,
    'D','R','A','W','R','3', 0xC2,
    'P','O','L','Y','R','3', 0xC6,
    'M','D','I','D','E','N', 0xCF,
    'M','D','S','C','A','L', 0xD1,
    'M','D','R','O','T','X', 0xD2,
    'M','D','R','O','T','Y', 0xD3,
    'M','D','R','O','T','Z', 0xD4,
    'M','D','T','R','A','N', 0xD5,
    'M','D','M','A','T','X', 0xD6,
    'V','W','I','D','E','N', 0xD7,
    'V','W','R','O','T','X', 0xD9,
    'V','W','R','O','T','Y', 0xDA,
    'V','W','R','O','T','Z', 0xDB,
    'V','W','M','A','T','X', 0xDC,
    'C','O','N','V','R','T', 0xE1,
    'P','R','O','J','C','T', 0xE2,
    'D','I','S','T','A','N', 0xE3,
    'V','W','P','O','R','T', 0xE4,
    'W','I','N','D','O','W', 0xE5,
    'P','R','M','F','I','L', 0xE6,
    'L','I','N','F','U','N', 0xE7,
    'F','L','A','G','R','D', 0xE8,
    'M','A','T','X','R','D', 0xE9,
    'A','R','E','A','B','C', 0xEC,
    'T','A','N','G','L','E', 0xEF,
    'T','D','E','F','I','N', 0xF0,
    'E','L','I','P','S','E', 0xF1,
    'L','I','N','P','A','T', 0xF2,
    'F','L','O','O','D', 0xB8,
    'M','O','V','E','R', 0xBC,
    'M','O','V','E','3', 0xBD,
    'D','R','A','W','R', 0xC0,
    'D','R','A','W','3', 0xC1,
    'P','O','L','Y','R', 0xC4,
    'P','O','L','Y','3', 0xC5,
    'R','E','C','T','R', 0xC8,
    'C','L','B','E','G', 0xC9,
    'C','L','E','N','D', 0xCA,
    'C','L','R','U','N', 0xCB,
    'C','L','O','O','P', 0xCC,
    'C','L','D','E','L', 0xCD,
    'C','L','A','P','P', 0xCE,
    'M','D','O','R','G', 0xD0,
    'V','W','R','P','T', 0xD8,
    'D','I','S','T','H', 0xDD,
    'D','I','S','T','Y', 0xDE,
    'C','L','I','P','H', 0xDF,
    'C','L','I','P','Y', 0xE0,
    'T','S','I','Z','E', 0xEE,
    'T','E','X','T','P', 0xF3,
    'T','J','U','S','T', 0xF4,
    'P','O','I','N','T', 0xF5,
    'F','L','I','P', 0xB4,
    'W','A','I','T', 0xB7,
    'M','O','V','E', 0xBB,
    'D','R','A','W', 0xBF,
    'P','O','L','Y', 0xC3,
    'R','E','C','T', 0xC7,
    'C','L','R','D', 0xEA,
    'A','R','E','A', 0xEB,
    'T','E','X','T', 0xED,
    0 };
char glvtab[] = {
    0x02, 0x00,   /* $B4 FLIP */
    0x03, 0x00,   /* $B5 PGSYNC */
    0x04, 0x00,   /* $B6 RESETF */
    0x05, 0x01,   /* $B7 WAIT */
    0x07, 0x30,   /* $B8 FLOOD */
    0x09, 0x00,   /* $B9 POINT3 */
    0x0F, 0x30,   /* $BA CLEARS */
    0x10, 0x02,   /* $BB MOVE */
    0x11, 0x02,   /* $BC MOVER */
    0x12, 0x03,   /* $BD MOVE3 */
    0x13, 0x03,   /* $BE MOVER3 */
    0x28, 0x02,   /* $BF DRAW */
    0x29, 0x02,   /* $C0 DRAWR */
    0x2A, 0x03,   /* $C1 DRAW3 */
    0x2B, 0x03,   /* $C2 DRAWR3 */
    0x30, 0x90,   /* $C3 POLY */
    0x31, 0x90,   /* $C4 POLYR */
    0x32, 0x90,   /* $C5 POLY3 */
    0x33, 0x90,   /* $C6 POLYR3 */
    0x34, 0x02,   /* $C7 RECT */
    0x35, 0x02,   /* $C8 RECTR */
    0x70, 0x10,   /* $C9 CLBEG */
    0x71, 0x00,   /* $CA CLEND */
    0x72, 0x10,   /* $CB CLRUN */
    0x73, 0x11,   /* $CC CLOOP */
    0x74, 0x10,   /* $CD CLDEL */
    0x79, 0x10,   /* $CE CLAPP */
    0x90, 0x00,   /* $CF MDIDEN */
    0x91, 0x03,   /* $D0 MDORG */
    0x92, 0x03,   /* $D1 MDSCAL */
    0x93, 0x01,   /* $D2 MDROTX */
    0x94, 0x01,   /* $D3 MDROTY */
    0x95, 0x01,   /* $D4 MDROTZ */
    0x96, 0x03,   /* $D5 MDTRAN */
    0x97, 0x0C,   /* $D6 MDMATX */
    0xA0, 0x00,   /* $D7 VWIDEN */
    0xA1, 0x03,   /* $D8 VWRPT */
    0xA3, 0x01,   /* $D9 VWROTX */
    0xA4, 0x01,   /* $DA VWROTY */
    0xA5, 0x01,   /* $DB VWROTZ */
    0xA7, 0x09,   /* $DC VWMATX */
    0xA8, 0x01,   /* $DD DISTH */
    0xA9, 0x01,   /* $DE DISTY */
    0xAA, 0x10,   /* $DF CLIPH */
    0xAB, 0x10,   /* $E0 CLIPY */
    0xAF, 0x00,   /* $E1 CONVRT */
    0xB0, 0x01,   /* $E2 PROJCT */
    0xB1, 0x01,   /* $E3 DISTAN */
    0xB2, 0x04,   /* $E4 VWPORT */
    0xB3, 0x04,   /* $E5 WINDOW */
    0xE0, 0x10,   /* $E6 PRMFIL */
    0xEB, 0x10,   /* $E7 LINFUN */
    0x61, 0x10,   /* $E8 FLAGRD */
    0x62, 0x10,   /* $E9 MATXRD */
    0x76, 0x10,   /* $EA CLRD */
    0xC0, 0x00,   /* $EB AREA */
    0xC1, 0x30,   /* $EC AREABC */
    0x80, 0xFF,   /* $ED TEXT */
    0x81, 0x01,   /* $EE TSIZE */
    0x82, 0x01,   /* $EF TANGLE */
    0x84, 0x10,   /* $F0 TDEFIN */
    0x39, 0x02,   /* $F1 ELIPSE */
    0xEA, 0x01,   /* $F2 LINPAT */
    0x83, 0xFF,   /* $F3 TEXTP */
    0x85, 0x20,   /* $F4 TJUST */
    0x08, 0x00,   /* $F5 POINT */
    0 };
