#!/usr/bin/env python3
"""Generate the disassembler's opcode table (os/commands/lib_distab.c) from
genucode.OPC — the same single source the microcode and the assembler table use,
so `disasm` never drifts from the real ISA.

Emits three parallel C globals scanned by disasm.c (spliced with `//#use distab`):
    int   dt_n;         number of entries
    int   dt_op[dt_n];  opcode byte
    int   dt_sh[dt_n];  operand shape (see below)
    char *dt_mn[dt_n];  mnemonic

shape -> operand form and instruction length:
    0 ""     len 1      6 (P2)+  len 1
    1 "#"    len 2      7 (P3)   len 1
    2 "a"    len 3      8 (P3)+  len 1
    3 (P1)   len 1      9 "a,a"  len 5   (MOVW dst,src / ADDW SUBW CMPW a,b)
    4 (P1)+  len 1
    5 (P2)   len 1
  Tier A (2026-09-11; byte stream = address word first, then imm/disp):
   10 "#w"        len 3   LDPn #imm16
   11..13 (Pn+d)  len 2   LDA/STA (Pn+d): op d8          (11=P1 12=P2 13=P3)
   14..16 a,(Pn+d) len 4  LDW a,(Pn+d):   op a.lo a.hi d8 (14=P1 15=P2 16=P3)
   17..19 (Pn+d),a len 4  STW (Pn+d),a:   op a.lo a.hi d8 (17=P1 18=P2 19=P3)
   20 "a,#"       len 4   LDW a,#imm8:    op a.lo a.hi imm8
   21 "a,#w"      len 5   LDW a,#imm16:   op a.lo a.hi imm.lo imm.hi
   22 "r"         len 2   Jcc rel8: op d8 (signed, from the next instruction)
  (This numbering is the DISASSEMBLER's; the native assembler's opcode table
  from gen_p8xopc.py has its own, where 9 is "#w".)

Usage: gen_p8xdis.py [out.c]   (defaults to os/commands/lib_distab.c)
"""
import sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "microcode"))
from genucode import OPC

SHAPE = {"": 0, "#": 1, "a": 2, "(P1)": 3, "(P1)+": 4, "(P2)": 5,
         "(P2)+": 6, "(P3)": 7, "(P3)+": 8, "a,a": 9,
         "#w": 10, "(P1+d)": 11, "(P2+d)": 12, "(P3+d)": 13,
         "a,(P1+d)": 14, "a,(P2+d)": 15, "a,(P3+d)": 16,
         "(P1+d),a": 17, "(P2+d),a": 18, "(P3+d),a": 19,
         "a,#": 20, "a,#w": 21, "r": 22}


def main():
    # reverse: opcode -> (mnemonic, shape). On an alias (JZ/BZ), prefer the
    # J-form (the mnemonic disassembly most people expect).
    rev = {}
    for (mn, sh), op in OPC.items():
        if sh not in SHAPE:
            sys.exit("gen_p8xdis: unknown shape %r for %s" % (sh, mn))
        if op not in rev or (mn.startswith("J") and not rev[op][0].startswith("J")):
            rev[op] = (mn, sh)
    rows = [(op, rev[op][0], SHAPE[rev[op][1]]) for op in sorted(rev)]

    # `--asm` emits the assembly table (os/commands-asm/lib_distab.inc) spliced into
    # disasm.asm by `;#use distab`; otherwise the C table (lib_distab.c, //#use).
    args = [a for a in sys.argv[1:] if a != "--asm"]
    asm = "--asm" in sys.argv[1:]

    if asm:
        out = open(args[0], "w") if args \
            else open(os.path.join(HERE, "..", "os", "commands-asm", "lib_distab.inc"), "w")
        w = out.write
        w("; lib_distab.inc -- disassembler opcode table (AUTO-GENERATED by\n")
        w(";   generators/gen_p8xdis.py --asm from genucode.OPC; mirrors lib_distab.c).\n")
        w(";   Spliced into disasm.asm by `;#use distab`. One record per opcode, scanned\n")
        w(";   by DIS_FIND:  .byte <opcode>,<shape> ; .asciiz \"MNEMONIC\".  $FF ends it.\n")
        w("DISTAB:\n")
        for op, mn, sh in rows:
            w("        .byte $%02X,%d\n" % (op, sh))
            w('        .asciiz "%s"\n' % mn)
        w("        .byte $FF\n")
        if out is not sys.stdout:
            out.close()
        return

    out = open(args[0], "w") if args \
        else open(os.path.join(HERE, "..", "os", "commands", "lib_distab.c"), "w")
    w = out.write
    w("/* lib_distab.c -- disassembler opcode table.\n")
    w(" * AUTO-GENERATED by generators/gen_p8xdis.py from genucode.OPC. Do not edit;\n")
    w(" * regenerate. Spliced into disasm.c by `//#use distab`. Stays in the p8cc\n")
    w(" * subset (globals + array-of-pointer initialisers only). */\n")
    w("int dt_n = %d;\n" % len(rows))
    w("int dt_op[%d] = {%s};\n" % (len(rows), ", ".join(str(op) for op, _, _ in rows)))
    w("int dt_sh[%d] = {%s};\n" % (len(rows), ", ".join(str(sh) for _, _, sh in rows)))
    w('char *dt_mn[%d] = {%s};\n' % (len(rows), ", ".join('"%s"' % mn for _, mn, _ in rows)))
    if out is not sys.stdout:
        out.close()


if __name__ == "__main__":
    main()
