#!/usr/bin/env python3
"""gen_glkw.py - single source of truth for the GL ASCII keyword table
(stage 10d, STAGE10-DESIGN.md).

Each verb: long form, short form (the PG-640A manual's, ch. 4), hex
opcode, BCNT (how many LEADING parameters are byte-width -- 0, 1 or 3;
every later parameter is int16 LE), ARITY (total parameter count; 15 =
variable: a POLY count byte, then count * (2 or 3) int16s by opcode
bit 1). CA/CX are mode switches handled inside the translators and get
the internal markers 0xFE/0xFF.

Emits:
  generators/glkwtab.h   (C)       -> #include'd by the emulator
  fpga/rtl/glkwtab.vh    (Verilog) -> `include'd inside p8x_geom's
                          scratchpad initial block: 4 halfwords per
                          entry at word 128 up -- chars 0-5 of the
                          keyword (space-padded), then
                          {var, arity[3:0], bcnt[1:0], opcode[7:0]}.
  basic/glkwtab.inc      (asm)     -> KWTAB fragment: the GL verbs as
                          native BASIC keywords, tokens GLV0 up IN
                          BASIC_VERBS ORDER, but LISTED longest-first
                          so CRUNCH's first-match never truncates
                          (MOVER3 before MOVER before MOVE; POINT3
                          and CLEARS precede the MAIN table's POINT
                          and CLS because this fragment is spliced at
                          the head of KWTAB).
  basic/glvtab.inc       (asm)     -> GLV0/GLVN equates + GLVTAB, two
                          bytes per verb in TOKEN order: opcode, then
                          {var<<7 | bcnt<<4 | word-arity}.

TOKEN ORDER IS ABI: saved .BAS files are tokenised, so BASIC_VERBS may
only be APPENDED to -- never reordered, never have entries removed.

Run:  python3 generators/gen_glkw.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

#        long      short  op    bcnt arity
VERBS = [
    ("NOOP",    "NOP",  0x01, 0, 0),
    ("FLIP",    "FL",   0x02, 0, 0),   # P8X page verbs
    ("PGSYNC",  "PS",   0x03, 0, 0),
    ("RESETF",  "RF",   0x04, 0, 0),
    ("WAIT",    "W",    0x05, 0, 1),
    ("COLOR",   "C",    0x06, 3, 3),
    ("FLOOD",   "F",    0x07, 3, 3),
    ("POINT",   "PT",   0x08, 0, 0),
    ("POINT3",  "PT3",  0x09, 0, 0),
    ("CLEARS",  "CLS",  0x0F, 3, 3),
    ("MOVE",    "M",    0x10, 0, 2),
    ("MOVER",   "MR",   0x11, 0, 2),
    ("MOVE3",   "M3",   0x12, 0, 3),
    ("MOVER3",  "MR3",  0x13, 0, 3),
    ("DRAW",    "D",    0x28, 0, 2),
    ("DRAWR",   "DR",   0x29, 0, 2),
    ("DRAW3",   "D3",   0x2A, 0, 3),
    ("DRAWR3",  "DR3",  0x2B, 0, 3),
    ("POLY",    "P",    0x30, 1, 15),
    ("POLYR",   "PR",   0x31, 1, 15),
    ("POLY3",   "P3",   0x32, 1, 15),
    ("POLYR3",  "PR3",  0x33, 1, 15),
    ("RECT",    "R",    0x34, 0, 2),
    ("RECTR",   "RR",   0x35, 0, 2),
    ("CLBEG",   "CB",   0x70, 1, 1),
    ("CLEND",   "CE",   0x71, 0, 0),
    ("CLRUN",   "CR",   0x72, 1, 1),
    ("CLOOP",   "CL",   0x73, 1, 2),
    ("CLDEL",   "CD",   0x74, 1, 1),
    ("CLAPP",   "CLA",  0x79, 1, 1),   # P8X append
    ("MDIDEN",  "MDI",  0x90, 0, 0),
    ("MDORG",   "MDO",  0x91, 0, 3),
    ("MDSCAL",  "MDS",  0x92, 0, 3),
    ("MDROTX",  "MDX",  0x93, 0, 1),
    ("MDROTY",  "MDY",  0x94, 0, 1),
    ("MDROTZ",  "MDZ",  0x95, 0, 1),
    ("MDTRAN",  "MDT",  0x96, 0, 3),
    ("MDMATX",  "MDM",  0x97, 0, 12),
    ("VWIDEN",  "VWI",  0xA0, 0, 0),
    ("VWRPT",   "VWR",  0xA1, 0, 3),
    ("VWROTX",  "VWX",  0xA3, 0, 1),
    ("VWROTY",  "VWY",  0xA4, 0, 1),
    ("VWROTZ",  "VWZ",  0xA5, 0, 1),
    ("VWMATX",  "VWM",  0xA7, 0, 9),
    ("DISTH",   "DH",   0xA8, 0, 1),
    ("DISTY",   "DY",   0xA9, 0, 1),
    ("CLIPH",   "CH",   0xAA, 1, 1),
    ("CLIPY",   "CY",   0xAB, 1, 1),
    ("CONVRT",  "CV",   0xAF, 0, 0),
    ("PROJCT",  "PRO",  0xB0, 0, 1),
    ("DISTAN",  "DS",   0xB1, 0, 1),
    ("VWPORT",  "VWP",  0xB2, 0, 4),
    ("WINDOW",  "WI",   0xB3, 0, 4),
    ("PRMFIL",  "PF",   0xE0, 1, 1),
    ("CA",      "CA",   0xFE, 0, 0),   # mode switches: internal markers
    ("CX",      "CX",   0xFF, 0, 0),
]

entries = []
for lng, sht, op, b, a in VERBS:
    entries.append((lng, op, b, a))
    if sht != lng:
        entries.append((sht, op, b, a))

with open(os.path.join(HERE, "glkwtab.h"), "w") as f:
    f.write("/* glkwtab.h - GENERATED by generators/gen_glkw.py. Do not edit. */\n")
    f.write("static const struct { const char *kw; uint8_t op, bcnt, arity; }\n")
    f.write("GLKW[] = {\n")
    for kw, op, b, a in entries:
        f.write('    { "%s", 0x%02X, %d, %d },\n' % (kw, op, b, a))
    f.write("};\n#define GLKWN %d\n" % len(entries))
print("wrote generators/glkwtab.h (%d entries)" % len(entries))

with open(os.path.join(HERE, "..", "fpga", "rtl", "glkwtab.vh"), "w") as f:
    f.write("// glkwtab.vh - GENERATED by generators/gen_glkw.py. Do not edit.\n")
    f.write("// Keyword ROM in the scratchpad, 4 halfwords per entry from word\n")
    f.write("// 128: chars 0-5 space-padded, then {var,arity[3:0],bcnt[1:0],op}.\n")
    w = 128
    for kw, op, b, a in entries:
        k = (kw + "      ")[:6]
        f.write("    cmx[%d] = 16'h%02X%02X;\n" % (w,   ord(k[0]), ord(k[1])))
        f.write("    cmx[%d] = 16'h%02X%02X;\n" % (w+1, ord(k[2]), ord(k[3])))
        f.write("    cmx[%d] = 16'h%02X%02X;\n" % (w+2, ord(k[4]), ord(k[5])))
        var = 1 if a == 15 else 0
        meta = (var << 14) | ((a & 15) << 10) | ((b & 3) << 8) | op
        f.write("    cmx[%d] = 16'h%04X;\n" % (w+3, meta))
        w += 4
    f.write("    // %d entries; the matcher stops at the first zero word\n" % len(entries))
    f.write("    cmx[%d] = 16'h0000;\n" % w)
print("wrote fpga/rtl/glkwtab.vh (ends at scratch word %d of 1024)" % (w+1))

# ---- BASIC's native GL statements ---------------------------------------
# Long forms only (BASIC style; GL "..." still takes the short forms).
# Excluded: NOOP (pointless), POINT (BASIC's POINT(x,y) function owns the
# name -- GL "POINT" remains), COLOR (BASIC's COLOR statement now feeds
# BOTH pens itself), CA/CX (mode plumbing the statement layer handles).
BASIC_SKIP = {"NOOP", "POINT", "COLOR", "CA", "CX"}
GLV0 = 0xB4
bverbs = [(l, op, b, a) for l, s, op, b, a in VERBS if l not in BASIC_SKIP]
assert GLV0 + len(bverbs) <= 0x100, "token space overflow"

with open(os.path.join(HERE, "..", "basic", "glkwtab.inc"), "w") as f:
    f.write("; glkwtab.inc - GENERATED by generators/gen_glkw.py. Do not edit.\n")
    f.write("; KWTAB fragment: GL verbs as native keywords, tokens $%02X up in\n" % GLV0)
    f.write("; BASIC_VERBS order (the token order is ABI). Listed LONGEST-FIRST\n")
    f.write("; so CRUNCH's first-match never truncates a longer keyword; the\n")
    f.write("; fragment sits at the head of KWTAB so POINT3/CLEARS beat the\n")
    f.write("; main table's POINT/CLS.\n")
    order = sorted(range(len(bverbs)), key=lambda i: -len(bverbs[i][0]))
    for i in order:
        f.write("        .ascii \"%s\"\n" % bverbs[i][0])
        f.write("        .byte $%02X\n" % (GLV0 + i))
print("wrote basic/glkwtab.inc (%d keywords)" % len(bverbs))

with open(os.path.join(HERE, "..", "basic", "glvtab.inc"), "w") as f:
    f.write("; glvtab.inc - GENERATED by generators/gen_glkw.py. Do not edit.\n")
    f.write("; Two bytes per verb in TOKEN order: the GL opcode, then\n")
    f.write("; {var<<7 | bcnt<<4 | word-arity}. var: a POLY count byte then\n")
    f.write("; count * (2 or 3 by opcode bit 1) int16s. Else bcnt byte params\n")
    f.write("; first, then (arity - bcnt) int16 params, little-endian.\n")
    f.write("GLV0   = $%02X\n" % GLV0)
    f.write("GLVN   = %d\n" % len(bverbs))
    f.write("GLVTAB:\n")
    for i, (lng, op, b, a) in enumerate(bverbs):
        if a == 15:
            meta = 0x80 | (b << 4)
        else:
            meta = (b << 4) | (a - b)
        f.write("        .byte $%02X, $%02X   ; $%02X %s\n"
                % (op, meta, GLV0 + i, lng))
print("wrote basic/glvtab.inc (GLV0=$%02X GLVN=%d)" % (GLV0, len(bverbs)))
