#!/usr/bin/env python3
"""Generate the P8X native assembler's opcode table from genucode.OPC.

The on-target assembler (apps/p8xasm.asm) needs the same (mnemonic, operand
shape) -> opcode mapping the microcode is built from. Rather than hand-copy 86
opcodes (and let them drift), this emits an assembly fragment defining OPCTAB,
which the build concatenates after the assembler logic.

Record format (one per opcode), scanned by the native ENTOPC routine:
    .byte <shapecode>, <opcode>
    .ascii "MNEMONIC"
    .byte 0
A trailing .byte $FF terminates the table.

shapecode encodes the operand form (must match the native parse_operand):
    0 ""   1 "#"   2 "a"
    3 (P1) 4 (P1)+ 5 (P2) 6 (P2)+ 7 (P3) 8 (P3)+
    9 "#w" -- a 16-bit immediate. The native parser never produces 9 from
      syntax; DO_LDP sets SHAPE=9 itself to look up the LDPn opcode (Tier A:
      LDPn #imm16 is a real 3-byte instruction, no longer an LPLn/LPHn pair).
The remaining Tier A shapes -- (Pn+d), a,(Pn+d), (Pn+d),a, a,# and a,#w --
are emitted by the HOST toolchain only (the compiler's idioms) and are skipped
here until the native operand parser grows them (backlog: ASM two-operand /
displacement support). NOTE: this numbering is the ASSEMBLER's; the
disassembler table (gen_p8xdis.py) has its own, where 9 is "a,a".

Usage: gen_p8xopc.py [out.asm]   (defaults to stdout)
"""
import sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "microcode"))
from genucode import OPC

SHAPE = {"": 0, "#": 1, "a": 2,
         "(P1)": 3, "(P1)+": 4, "(P2)": 5, "(P2)+": 6, "(P3)": 7, "(P3)+": 8,
         "#w": 9}
# host-only shapes (see the docstring): skipped, not an error
HOST_ONLY = {"a,a", "a,#", "a,#w",
             "(P1+d)", "(P2+d)", "(P3+d)",
             "a,(P1+d)", "a,(P2+d)", "a,(P3+d)",
             "(P1+d),a", "(P2+d),a", "(P3+d),a"}


def main():
    out = open(sys.argv[1], "w") if len(sys.argv) > 1 else sys.stdout
    w = out.write
    w("; ============================================================\n")
    w("; AUTO-GENERATED by generators/gen_p8xopc.py from genucode.OPC\n")
    w("; Do not edit — regenerate. Concatenated after p8xasm.asm.\n")
    w("; ============================================================\n")
    w("OPCTAB:\n")
    # stable order: by mnemonic then shape, for readable diffs
    for (mn, sh), op in sorted(OPC.items()):
        if sh in HOST_ONLY:
            # Two-operand / displacement ops (MOVW dst,src, the Tier A forms) —
            # the on-target assembler's parse_operand handles only the
            # single-operand shapes, so these are emitted by the HOST toolchain
            # only. Skip until the native parser grows them.
            continue
        if sh not in SHAPE:
            sys.exit("gen_p8xopc: unknown shape %r for %s" % (sh, mn))
        w("        .byte %d,$%02X\n" % (SHAPE[sh], op))
        w('        .ascii "%s"\n' % mn)
        w("        .byte 0\n")
    w("        .byte $FF\n")
    if out is not sys.stdout:
        out.close()


if __name__ == "__main__":
    main()
