#!/usr/bin/env python3
"""Generate the P8X native assembler's opcode table from genucode.OPC.

The on-target assembler (apps/p8xasm.asm) needs the same (mnemonic, operand
shape) -> opcode mapping the microcode is built from. Rather than hand-copy 86
opcodes (and let them drift), this emits an assembly fragment defining OPCTAB,
which the build concatenates after the assembler logic.

Record format (one per opcode), scanned by the native ENTOPC routine:
    .byte <shapecode>, <opcode>
    .ascii "MNEMONIC"
    .byte 0
A trailing .byte $FF terminates the table.

shapecode encodes the operand form (must match the native parse_operand):
    0 ""   1 "#"   2 "a"
    3 (P1) 4 (P1)+ 5 (P2) 6 (P2)+ 7 (P3) 8 (P3)+
    9 "#w" -- a 16-bit immediate. The native parser never produces 9 from
      syntax; DO_LDP sets SHAPE=9 itself to look up the LDPn opcode (Tier A:
      LDPn #imm16 is a real 3-byte instruction, no longer an LPLn/LPHn pair).
   10 "a,a"      MOVW/ADDW/SUBW/CMPW dst,src      (op a.lo a.hi b.lo b.hi)
   11 "a,#"      LDW/ADDW/SUBW/CMPW a,#imm8       (op a.lo a.hi imm8)
   12 "a,#w"     LDW a,#imm16                     (op a.lo a.hi imm.lo imm.hi)
   13 14 15      (P1+d) (P2+d) (P3+d)             (op d8)         LDA/STA
   16 17 18      a,(P1+d) a,(P2+d) a,(P3+d)       (op a.lo a.hi d8) LDW/LEAW
   19 20 21      (P1+d),a (P2+d),a (P3+d),a       (op a.lo a.hi d8) STW
   (2026-09-11, os-rewrite step 0: the native PARSEOP grew a second operand
   and the displacement form; imm8 vs imm16 for shape 11/12 is decided from
   the operand TEXT exactly as the host's lit8() does, so the two assemblers
   stay byte-identical.) Only "r" (relative branches: host-side relaxation)
   remains host-only. NOTE: this numbering is the ASSEMBLER's; the
   disassembler table (gen_p8xdis.py) has its own, where 9 is "a,a".

Usage: gen_p8xopc.py [out.asm]   (defaults to stdout)
"""
import sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "microcode"))
from genucode import OPC

SHAPE = {"": 0, "#": 1, "a": 2,
         "(P1)": 3, "(P1)+": 4, "(P2)": 5, "(P2)+": 6, "(P3)": 7, "(P3)+": 8,
         "#w": 9, "a,a": 10, "a,#": 11, "a,#w": 12,
         "(P1+d)": 13, "(P2+d)": 14, "(P3+d)": 15,
         "a,(P1+d)": 16, "a,(P2+d)": 17, "a,(P3+d)": 18,
         "(P1+d),a": 19, "(P2+d),a": 20, "(P3+d),a": 21}
# host-only shapes (see the docstring): skipped, not an error
HOST_ONLY = {"r"}


def main():
    out = open(sys.argv[1], "w") if len(sys.argv) > 1 else sys.stdout
    w = out.write
    w("; ============================================================\n")
    w("; AUTO-GENERATED by generators/gen_p8xopc.py from genucode.OPC\n")
    w("; Do not edit — regenerate. Concatenated after p8xasm.asm.\n")
    w("; ============================================================\n")
    w("OPCTAB:\n")
    # stable order: by mnemonic then shape, for readable diffs
    for (mn, sh), op in sorted(OPC.items()):
        if sh in HOST_ONLY:
            # Two-operand / displacement ops (MOVW dst,src, the Tier A forms) —
            # the on-target assembler's parse_operand handles only the
            # single-operand shapes, so these are emitted by the HOST toolchain
            # only. Skip until the native parser grows them.
            continue
        if sh not in SHAPE:
            sys.exit("gen_p8xopc: unknown shape %r for %s" % (sh, mn))
        w("        .byte %d,$%02X\n" % (SHAPE[sh], op))
        w('        .ascii "%s"\n' % mn)
        w("        .byte 0\n")
    w("        .byte $FF\n")
    if out is not sys.stdout:
        out.close()


if __name__ == "__main__":
    main()
