#!/usr/bin/env python3
"""gen_chargen.py - the hardware text-overlay CHARACTER GENERATOR ROM.

The graphics card grows a text-overlay plane (a classic 6845-style
character generator composited over the GL bitmap at scanout): a grid of
ASCII cells, each cell turned into pixels on the fly by a small ROM of
glyph bitmaps. This generator BUILDS that ROM.

Single source of truth (hard-rule 1): the glyph SHAPES come from
gen_font.py's `F` -- the very same stroke polylines the GL stroke font is
built from -- rasterised onto the overlay's fixed cell grid. So the
hardware text plane and the GL-drawn text render the SAME letterforms;
there is no second font to drift.

Cell geometry (v1), chosen to line up with the existing 80-column glass
TTY and the font's native advance of 6:
  - CELL_W = 6, CELL_H = 8   -> 480/6 = 80 cols, 272/8 = 34 rows exactly.
  - The font design grid is x 0..4 (5 wide, +1 col gap) and y -1..6
    (baseline y=0, caps to y=6, descenders to y=-1) -> 8 rows top-to-
    bottom with descenders captured and a 1px gap under the caps.
  - Coverage: codes 32..127 (96 glyphs). 32..95 come straight from F;
    lowercase 97..122 FOLDS to uppercase (as the glass TTY already does);
    everything else undefined in F (`` ` `` { | } ~ DEL) renders blank.

Bit layout: one byte per glyph row, top row first. Pixel column c (0..5)
is bit (5-c) -- so x=0 is bit 5 and the cell is left-justified; bit 0 is
the inter-character gap column and stays 0. Bits 7,6 are unused (0).

Outputs (both GENERATED, do not edit):
  - generators/chargen.h            -- `static const uint8_t CHARGEN[...]`
                                       for the emulator (golden model).
  - generators/chargen.hex          -- $readmemh image for the RTL char-
                                       gen block ROM (8-bit words).

Run:  python3 generators/gen_chargen.py           # writes both
      python3 generators/gen_chargen.py --preview  # + ASCII-art proof
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from gen_font import F                      # the ONE glyph-shape source

CELL_W = 6
CELL_H = 8
LO = 32                                     # first code in the ROM
HI = 128                                    # one past the last (32..127)
N = HI - LO                                 # 96 glyphs


def glyph_polys(code):
    """The stroke polylines for a character code, folding lowercase to
    uppercase and leaving anything F does not define blank."""
    ch = chr(code)
    if 97 <= code <= 122:                   # a..z -> A..Z, as TEXT does
        ch = chr(code - 32)
    return F.get(ch, [])


def raster(polys):
    """Rasterise stroke polylines (design coords) onto the CELL_H x CELL_W
    bit grid. Returns (rom_bytes[CELL_H], grid[CELL_H][CELL_W]) where a set
    grid cell is an inked pixel."""
    grid = [[0] * CELL_W for _ in range(CELL_H)]

    def plot(x, y):
        col = x                             # design x 0..4 -> cell col 0..4
        row = 6 - y                         # y=6 (cap top) -> row 0; y=-1 -> row 7
        if 0 <= row < CELL_H and 0 <= col < CELL_W:
            grid[row][col] = 1

    def line(x0, y0, x1, y1):               # integer Bresenham, short segs
        dx = abs(x1 - x0)
        dy = abs(y1 - y0)
        sx = 1 if x0 < x1 else -1
        sy = 1 if y0 < y1 else -1
        err = dx - dy
        while True:
            plot(x0, y0)
            if x0 == x1 and y0 == y1:
                break
            e2 = 2 * err
            if e2 > -dy:
                err -= dy
                x0 += sx
            if e2 < dx:
                err += dx
                y0 += sy

    for poly in polys:
        if len(poly) == 1:                  # a dot -> one pixel
            plot(*poly[0])
        else:
            for (ax, ay), (bx, by) in zip(poly, poly[1:]):
                line(ax, ay, bx, by)

    rom = []
    for row in range(CELL_H):
        byte = 0
        for col in range(CELL_W):
            if grid[row][col]:
                byte |= 1 << (5 - col)      # x=0 -> bit5, left-justified
        rom.append(byte)
    return rom, grid


def build():
    """Return (rom, grids): rom is N*CELL_H bytes, grids[i] the bit grid."""
    rom = []
    grids = []
    for code in range(LO, HI):
        bytes_, grid = raster(glyph_polys(code))
        rom.extend(bytes_)
        grids.append(grid)
    return rom, grids


def write_header(rom):
    out = os.path.join(HERE, "chargen.h")
    with open(out, "w", newline="\n") as f:
        f.write("/* chargen.h - GENERATED by generators/gen_chargen.py."
                " Do not edit. */\n")
        f.write("/* Hardware text-overlay character generator: %d glyphs "
                "(codes %d..%d),\n" % (N, LO, HI - 1))
        f.write(" * a %dx%d cell, one byte per row (top first), pixel col c"
                " = bit (5-c). */\n" % (CELL_W, CELL_H))
        f.write("#define CHARGEN_CW %d\n" % CELL_W)
        f.write("#define CHARGEN_CH %d\n" % CELL_H)
        f.write("#define CHARGEN_LO %d\n" % LO)
        f.write("#define CHARGEN_N  %d\n" % N)
        f.write("static const uint8_t CHARGEN[%d] = {\n" % (N * CELL_H))
        for i in range(N):
            code = LO + i
            row = rom[i * CELL_H:(i + 1) * CELL_H]
            body = " ".join("0x%02X," % b for b in row)
            ch = chr(code)
            label = ch if 33 <= code <= 126 else ("sp" if code == 32 else "?")
            f.write("    %s  /* %3d '%s' */\n" % (body, code, label))
        f.write("};\n")
    return out


def write_hex(rom):
    out = os.path.join(HERE, "chargen.hex")
    with open(out, "w", newline="\n") as f:
        f.write("// chargen.hex - GENERATED by generators/gen_chargen.py."
                " $readmemh image, 8-bit words.\n")
        for i in range(N):
            row = rom[i * CELL_H:(i + 1) * CELL_H]
            f.write(" ".join("%02x" % b for b in row) +
                    ("   // %d\n" % (LO + i)))
    return out


def write_vh(rom):
    """The RTL char-gen ROM as includable Verilog init lines (the glkwtab.vh /
    trigtab.v convention -- `include'd inside gtxt.v's initial block, so no
    $readmemh path juggling across sim/synth cwds)."""
    out = os.path.join(HERE, "..", "fpga", "rtl", "chargen.vh")
    with open(out, "w", newline="\n") as f:
        f.write("// chargen.vh - GENERATED by generators/gen_chargen.py."
                " Do not edit.\n")
        f.write("// Text-overlay char-gen ROM: %d glyphs (codes %d..%d), %dx%d"
                " cell, 8 rows/glyph,\n" % (N, LO, HI - 1, CELL_W, CELL_H))
        f.write("// one byte per row (top first), pixel col c = bit (5-c)."
                " `include'd into an\n")
        f.write("// initial block filling  reg [7:0] chargen [0:%d].\n"
                % (N * CELL_H - 1))
        for i in range(N):
            code = LO + i
            for r in range(CELL_H):
                f.write("chargen[%d] = 8'h%02X;%s\n" % (
                    i * CELL_H + r, rom[i * CELL_H + r],
                    ("   // %d '%s' row0" % (code, chr(code)))
                    if r == 0 and 33 <= code <= 126 else ""))
    return out


def preview(grids, s):
    """ASCII-art proof: render a string with the rasterised ROM."""
    rows = ["" for _ in range(CELL_H)]
    for ch in s:
        code = ord(ch)
        g = grids[code - LO] if LO <= code < HI else [[0] * CELL_W] * CELL_H
        for r in range(CELL_H):
            rows[r] += "".join("#" if g[r][c] else "." for c in range(CELL_W))
            rows[r] += " "
    print("  " + ("-" * (len(s) * (CELL_W + 1))))
    for r in rows:
        print("  " + r)


def main():
    rom, grids = build()
    h = write_header(rom)
    x = write_hex(rom)
    v = write_vh(rom)
    print("wrote %s (%d bytes)" % (os.path.relpath(h), N * CELL_H))
    print("wrote %s" % os.path.relpath(x))
    print("wrote %s" % os.path.relpath(v))
    if "--preview" in sys.argv:
        print("\nchar-gen preview (%dx%d cell):" % (CELL_W, CELL_H))
        preview(grids, "P8X TERM")
        preview(grids, "Hello, world!")
        preview(grids, "0123456789")
        preview(grids, "abcdefghijklm")


if __name__ == "__main__":
    main()
