#!/usr/bin/env python3
"""gen_trig.py - single source of truth for the stage-10b trig tables.

The GL matrix verbs (MDROTX/Y/Z, VWROTX/Y/Z, PROJCT - STAGE10-DESIGN.md)
need sin/cos and tan(angle/2) as 8.8 fixed point. The emulator and the RTL
must agree on EVERY entry or the pixel byte-compares die, so both read the
same generated tables:

  generators/trigtab.h    (C)       -> #include'd by the emulator
  fpga/rtl/trigtab.v      (Verilog) -> plain combinational ROM modules,
                             listed as an ordinary source (no include paths)

  SIN8[d]  = round(256 * sin(d degrees)),   d = 0..359   (signed, +-256)
  TANH8[a] = round(256 * tan(a/2 degrees)), a = 0..179   (0..29335)
             (indexed by the WHOLE PROJCT angle, so odd angles lose nothing)

Run:  python3 generators/gen_trig.py
"""
import math, os

HERE = os.path.dirname(os.path.abspath(__file__))

sin8 = [round(256 * math.sin(math.radians(d))) for d in range(360)]
tanh8 = [round(256 * math.tan(math.radians(a / 2.0))) for a in range(180)]

def rows(vals, per, fmt):
    out = []
    for i in range(0, len(vals), per):
        out.append(" " + " ".join(fmt % v for v in vals[i:i+per]))
    return "\n".join(out)

with open(os.path.join(HERE, "trigtab.h"), "w") as f:
    f.write("/* trigtab.h - GENERATED by generators/gen_trig.py. Do not edit. */\n")
    f.write("static const int16_t SIN8[360] = {\n")
    f.write(rows(sin8, 10, "%6d,"))
    f.write("\n};\n")
    f.write("static const int16_t TANH8[180] = {\n")
    f.write(rows(tanh8, 10, "%6d,"))
    f.write("\n};\n")
print("wrote generators/trigtab.h")
with open(os.path.join(HERE, "..", "fpga", "rtl", "trigtab.v"), "w") as f:
    f.write("// trigtab.v - GENERATED by generators/gen_trig.py. Do not edit.\n")
    f.write("// SIN8: round(256*sin(d deg)), d 0..359; TANH8: round(256*tan(a/2 deg)).\n")
    f.write("// CLOCKED rom reads so synthesis lands them in BSRAM, not LUTs\n")
    f.write("// (a 360-entry case cost ~1k LUT4 and broke placement at stage 10b).\n")
    f.write("// Callers must hold the address stable one cycle before use -- the\n")
    f.write("// compose FSM does (C_NRM precedes C_BLD; PROJCT is long latched).\n")
    f.write("// ONE dual-port block serves sin AND cos (the two reads the\n")
    f.write("// compose FSM needs in the same cycle) -- half the BSRAM.\n")
    f.write("module trig_sin(input clk, input [8:0] d, input [8:0] d2,\n")
    f.write("                output reg signed [15:0] q, output reg signed [15:0] q2);\n")
    f.write("  reg [15:0] rom [0:511];\n  integer i;\n  initial begin\n")
    f.write("    for (i = 0; i < 512; i = i + 1) rom[i] = 0;\n")
    for d, v in enumerate(sin8):
        f.write("    rom[%d] = 16'h%04X;\n" % (d, v & 0xFFFF))
    f.write("  end\n  always @(posedge clk) begin q <= rom[d]; q2 <= rom[d2]; end\nendmodule\n")
    f.write("module trig_tanh(input clk, input [7:0] a, output reg signed [15:0] q);\n")
    f.write("  reg [15:0] rom [0:255];\n  integer i;\n  initial begin\n")
    f.write("    for (i = 0; i < 256; i = i + 1) rom[i] = 0;\n")
    for a, v in enumerate(tanh8):
        f.write("    rom[%d] = 16'h%04X;\n" % (a, v & 0xFFFF))
    f.write("  end\n  always @(posedge clk) q <= rom[a];\nendmodule\n")
print("wrote fpga/rtl/trigtab.v (clocked ROMs)")
