#!/usr/bin/env python3
"""Generate the P8X native assembler's opcode table from genucode.OPC.

The on-target assembler (apps/p8xasm.asm) needs the same (mnemonic, operand
shape) -> opcode mapping the microcode is built from. Rather than hand-copy 86
opcodes (and let them drift), this emits an assembly fragment defining OPCTAB,
which the build concatenates after the assembler logic.

Record format (one per opcode), scanned by the native ENTOPC routine:
    .byte <shapecode>, <opcode>
    .ascii "MNEMONIC"
    .byte 0
A trailing .byte $FF terminates the table.

shapecode encodes the operand form (must match the native parse_operand):
    0 ""   1 "#"   2 "a"
    3 (P1) 4 (P1)+ 5 (P2) 6 (P2)+ 7 (P3) 8 (P3)+

Usage: gen_p8xopc.py [out.asm]   (defaults to stdout)
"""
import sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "microcode"))
from genucode import OPC

SHAPE = {"": 0, "#": 1, "a": 2,
         "(P1)": 3, "(P1)+": 4, "(P2)": 5, "(P2)+": 6, "(P3)": 7, "(P3)+": 8}


def main():
    out = open(sys.argv[1], "w") if len(sys.argv) > 1 else sys.stdout
    w = out.write
    w("; ============================================================\n")
    w("; AUTO-GENERATED by generators/gen_p8xopc.py from genucode.OPC\n")
    w("; Do not edit — regenerate. Concatenated after p8xasm.asm.\n")
    w("; ============================================================\n")
    w("OPCTAB:\n")
    # stable order: by mnemonic then shape, for readable diffs
    for (mn, sh), op in sorted(OPC.items()):
        if sh not in SHAPE:
            sys.exit("gen_p8xopc: unknown shape %r for %s" % (sh, mn))
        w("        .byte %d,$%02X\n" % (SHAPE[sh], op))
        w('        .ascii "%s"\n' % mn)
        w("        .byte 0\n")
    w("        .byte $FF\n")
    if out is not sys.stdout:
        out.close()


if __name__ == "__main__":
    main()
