#!/usr/bin/env python3
"""gen_trig.py - single source of truth for the stage-10b trig tables.

The GL matrix verbs (MDROTX/Y/Z, VWROTX/Y/Z, PROJCT - STAGE10-DESIGN.md)
need sin/cos and tan(angle/2) as 8.8 fixed point. The emulator and the RTL
must agree on EVERY entry or the pixel byte-compares die, so both read the
same generated tables:

  generators/trigtab.h    (C)       -> #include'd by the emulator
  fpga/rtl/trigtab.vh     (Verilog) -> `include'd by p8x_geom.v (function ROMs)

  SIN8[d]  = round(256 * sin(d degrees)),   d = 0..359   (signed, +-256)
  TANH8[a] = round(256 * tan(a/2 degrees)), a = 0..179   (0..29335)
             (indexed by the WHOLE PROJCT angle, so odd angles lose nothing)

Run:  python3 generators/gen_trig.py
"""
import math, os

HERE = os.path.dirname(os.path.abspath(__file__))

sin8 = [round(256 * math.sin(math.radians(d))) for d in range(360)]
tanh8 = [round(256 * math.tan(math.radians(a / 2.0))) for a in range(180)]

def rows(vals, per, fmt):
    out = []
    for i in range(0, len(vals), per):
        out.append(" " + " ".join(fmt % v for v in vals[i:i+per]))
    return "\n".join(out)

with open(os.path.join(HERE, "trigtab.h"), "w") as f:
    f.write("/* trigtab.h - GENERATED by generators/gen_trig.py. Do not edit. */\n")
    f.write("static const int16_t SIN8[360] = {\n")
    f.write(rows(sin8, 10, "%6d,"))
    f.write("\n};\n")
    f.write("static const int16_t TANH8[180] = {\n")
    f.write(rows(tanh8, 10, "%6d,"))
    f.write("\n};\n")
print("wrote generators/trigtab.h")

with open(os.path.join(HERE, "..", "fpga", "rtl", "trigtab.vh"), "w") as f:
    f.write("// trigtab.vh - GENERATED by generators/gen_trig.py. Do not edit.\n")
    f.write("// SIN8: round(256*sin(d deg)), d 0..359; TANH8: round(256*tan(a/2 deg)).\n")
    f.write("function signed [15:0] SIN8(input [8:0] d);\n  case (d)\n")
    for d, v in enumerate(sin8):
        f.write("    9'd%d: SIN8 = -16'sd%d;\n" % (d, -v) if v < 0
                else "    9'd%d: SIN8 = 16'sd%d;\n" % (d, v))
    f.write("    default: SIN8 = 16'sd0;\n  endcase\nendfunction\n")
    f.write("function signed [15:0] TANH8(input [7:0] a);\n  case (a)\n")
    for a, v in enumerate(tanh8):
        f.write("    8'd%d: TANH8 = 16'sd%d;\n" % (a, v))
    f.write("    default: TANH8 = 16'sd0;\n  endcase\nendfunction\n")
print("wrote fpga/rtl/trigtab.vh")
