#!/usr/bin/env python3
"""kicad_tools.py -- shared KiCad pipeline steps for the generic card boards
(companion to gen_kicad.py). Run under KiCad's bundled python (needs pcbnew;
some steps shell out to kicad-cli). Subcommands:

    export_dsn  <board.kicad_pcb>          -> <board>.dsn (In1/In2 marked power)
    import_ses  <board.kicad_pcb> <ses>    -> import routing, re-fill planes, save
    placement   <board.kicad_pcb>          -> <dir>/<...>-placement.pdf (centred, B/W)
    finish      <board.kicad_pcb>          -> gerbers zip + top/3d renders + placement

These mirror the memory card's bespoke scripts, generalised to any board path.
"""
import os, sys, subprocess, pcbnew
try:
    import wx; _app = wx.App()
except Exception:
    pass
CLI = "/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli"

def _run(*a):
    subprocess.run(list(a), check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

def export_dsn(brd):
    dsn = brd[:-len(".kicad_pcb")] + ".dsn"
    b = pcbnew.LoadBoard(brd)
    for z in b.Zones():
        z.UnFill()                                   # simple plane rects (optimiser-friendly)
    pcbnew.ExportSpecctraDSN(b, dsn)
    t = open(dsn).read()
    for lyr in ("In1.Cu", "In2.Cu"):
        t = t.replace("(layer %s\n      (type signal)" % lyr,
                      "(layer %s\n      (type power)" % lyr)
    open(dsn, "w").write(t)
    print("export_dsn ->", dsn)

def stitch_trivial_nets(b):
    """Self-heal: Freerouting occasionally leaves a trivial 2-pad net unrouted
    (e.g. an LED-bank resistor->LED at the board edge, whose direct top path is
    blocked by another track). Stitch any 2-pad net that has no copper AND whose
    pads are collinear with a straight B.Cu track -- through-hole pads let it duck
    under the F.Cu tracks. Returns the number stitched. Call after ImportSpecctraSES
    and before the zone fill. Shared by every card's import step."""
    b.BuildConnectivity()
    np = {}
    for fp in b.GetFootprints():
        for p in fp.Pads():
            np.setdefault(p.GetNetname(), []).append(p)
    n = 0
    for name, pads in np.items():
        if name in ("", "GND", "VCC") or len(pads) != 2:
            continue
        if any(t.GetNetname() == name for t in b.GetTracks()):
            continue
        a, c = pads
        if a.GetPosition().x != c.GetPosition().x and a.GetPosition().y != c.GetPosition().y:
            continue                                    # only stitch straight (collinear) runs
        t = pcbnew.PCB_TRACK(b)
        t.SetStart(a.GetPosition()); t.SetEnd(c.GetPosition())
        t.SetLayer(pcbnew.B_Cu); t.SetWidth(pcbnew.FromMM(0.25)); t.SetNetCode(a.GetNetCode())
        b.Add(t); n += 1
        print("  stitched %s: %s.%s -> %s.%s" % (name,
              a.GetParentFootprint().GetReference(), a.GetNumber(),
              c.GetParentFootprint().GetReference(), c.GetNumber()))
    if n:
        print("stitched %d trivial unrouted 2-pad net(s)" % n)
    return n

def import_ses(brd, ses):
    b = pcbnew.LoadBoard(brd)
    pcbnew.ImportSpecctraSES(b, ses)
    stitch_trivial_nets(b)                              # finish any net the router missed
    pcbnew.ZONE_FILLER(b).Fill(b.Zones())
    pcbnew.SaveBoard(brd, b)
    b.BuildConnectivity()
    ntrk = sum(1 for t in b.GetTracks() if t.Type() == pcbnew.PCB_TRACE_T)
    nvia = sum(1 for t in b.GetTracks() if t.Type() == pcbnew.PCB_VIA_T)
    print("import_ses: %d tracks, %d vias" % (ntrk, nvia))

def placement(brd):
    b = pcbnew.LoadBoard(brd)
    bb = b.GetBoardEdgesBoundingBox()
    bw = pcbnew.ToMM(bb.GetWidth())
    paper, pw, ph = ("A4", 297.0, 210.0) if bw <= 280 else ("A3", 420.0, 297.0)
    c = bb.GetCenter()
    shift = pcbnew.VECTOR2I(pcbnew.FromMM(pw) // 2 - c.x, pcbnew.FromMM(ph) // 2 - c.y)
    for it in (list(b.GetFootprints()) + list(b.GetTracks())
               + list(b.GetDrawings()) + list(b.Zones())):
        it.Move(shift)
    name = os.path.basename(brd)[:-len(".kicad_pcb")]
    tmp = "/tmp/%s-placement.kicad_pcb" % name
    pcbnew.SaveBoard(tmp, b)
    tb = ('  (title_block\n    (title "%s -- Parts Placement")\n'
          '    (company "P8X")\n  )\n' % name)
    t = open(tmp).read()
    if paper == "A3":
        t = t.replace('(paper "A4")', '(paper "A3")', 1)
    t = t.replace('(paper "%s")\n' % paper, '(paper "%s")\n' % paper + tb, 1)
    open(tmp, "w").write(t)
    out = os.path.join(os.path.dirname(brd), name + "-placement.pdf")
    _run(CLI, "pcb", "export", "pdf", "--layers", "F.Silkscreen,F.Fab,Edge.Cuts",
         "--black-and-white", "--include-border-title", "-o", out, tmp)
    os.remove(tmp)
    print("placement ->", out)

def _boilerplate(d, name):
    gi=os.path.join(d,".gitignore")
    open(gi,"w").write("gerbers/\n*.dsn\n*.kicad_prl\n*.rpt\nfr.log\nlogs/\n")
    rd=os.path.join(d,"README.md")
    if not os.path.exists(rd):
        card=name.replace("p8x-","")
        open(rd,"w").write(
"# %s -- KiCad\n\n"
"Generated by `generators/gen_kicad.py` from the canonical gen_eagle netlist\n"
"(`CARDS[\"%s\"]`), same standard as the memory card: 4-layer (F/B signals,\n"
"In1=GND, In2=VCC planes), a bypass cap above each IC, a labelled LED/jumper bank,\n"
"part values on silk. Routed with Freerouting. GENERATORS ARE CANON -- edit\n"
"`gen_kicad.py` and re-run `generators/build_kicad_card.sh %s`.\n\n"
"| File | What |\n|------|------|\n"
"| `p8x-%s.kicad_pcb` | the board |\n"
"| `p8x-%s.ses` | the Freerouting routing |\n"
"| `p8x-%s-gerbers.zip` | orderable gerbers |\n"
"| `p8x-%s-placement.pdf` | parts placement (refs+values) |\n"
"| `p8x-%s-render-top.png` / `-3d.png` | renders |\n\n"
"Exotic parts use the closest standard KiCad footprint (flagged when built).\n"
% (card,card,card,card,card,card,card,card))

def finish(brd):
    d = os.path.dirname(brd); name = os.path.basename(brd)[:-len(".kicad_pcb")]
    ger = os.path.join(d, "gerbers"); zipf = os.path.join(d, name + "-gerbers.zip")
    if os.path.isdir(ger):
        for f in os.listdir(ger): os.remove(os.path.join(ger, f))
    _run(CLI, "pcb", "export", "gerbers", "--no-protel-ext", "-o", ger + "/", brd)
    _run(CLI, "pcb", "export", "drill", "--format", "excellon", "--excellon-units", "mm", "-o", ger + "/", brd)
    if os.path.exists(zipf): os.remove(zipf)
    import glob, zipfile
    with zipfile.ZipFile(zipf, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(glob.glob(ger + "/*.gbr") + glob.glob(ger + "/*.gbrjob") + glob.glob(ger + "/*.drl")):
            z.write(f, os.path.basename(f))
    _run(CLI, "pcb", "render", "--side", "top", "--quality", "high", "--floor",
         "-w", "1800", "-h", "1000", "-o", os.path.join(d, name + "-render-top.png"), brd)
    _run(CLI, "pcb", "render", "--rotate", "-25,0,22", "--perspective", "--quality", "high", "--floor",
         "-w", "1800", "-h", "1100", "-o", os.path.join(d, name + "-render-3d.png"), brd)
    placement(brd)
    _boilerplate(d, name)
    print("finish: gerbers + renders + placement for", name)

if __name__ == "__main__":
    cmd = sys.argv[1]
    if cmd == "export_dsn": export_dsn(sys.argv[2])
    elif cmd == "import_ses": import_ses(sys.argv[2], sys.argv[3])
    elif cmd == "placement": placement(sys.argv[2])
    elif cmd == "finish": finish(sys.argv[2])
    else: sys.exit("unknown cmd " + cmd)
    sys.stdout.flush(); os._exit(0)   # skip the wx.App event-loop exit hang (work is saved)
