# memmap.py - GENERATED by generators/gen_memmap.py. Do not edit.


# memory-region anchors
RAMBASE     = 0x2000             # first RAM address (OS + scratch + TPA live here)
IOBASE      = 0xFF00             # memory-mapped I/O page
ROMSIZE     = 0x2000             # 8K firmware ROM $0000-$1FFF
RAMSIZE     = 0xDF00             # RAM span $2000-$FEFF (IOBASE-RAMBASE)
OSORG       = 0x2000             # OS load/link address (= RAMBASE)
TPABASE     = 0x6A00             # transient program area base (RUNnable programs load here)
CSTACKTOP   = 0xF800             # compiler C-stack top (grows down; p8cc __csp init)

# I/O ports ($FF00-$FFFF)
ACIAS       = 0xFF04             # ACIA status (rd) / control (wr)
ACIAD       = 0xFF05             # ACIA data
CFDATA      = 0xFF10             # CF task file
CFFEAT      = 0xFF11
CFSCNT      = 0xFF12
CFLBA0      = 0xFF13
CFLBA1      = 0xFF14
CFLBA2      = 0xFF15
CFHEAD      = 0xFF16             # $E0 = LBA mode, drive 0
CFCMD       = 0xFF17             # command (wr) / status (rd)
CFSTAT      = 0xFF17
GX0         = 0xFF20             # draw X0 / SETPAL red   (0-479)
GY0         = 0xFF21             # draw Y0 / SETPAL green (0-271)
GX1         = 0xFF22             # draw X1 / SETPAL blue  (0-479)
GY1         = 0xFF23             # draw Y1 (0-271)
GCOL        = 0xFF24             # pen LOW byte -- the pen is a whole RGB565 colour (see GCOLH)
GCMD        = 0xFF25             # write executes: 1 PLOT 2 LINE 3 BOX 4 BOXFILL 5 CLS 7 CIRCLE 8 CIRCLEFILL 9 POINT A ELLIPSE B ELLIPSEFILL / F1 RESET F2 IDENT
GSTAT       = 0xFF26             # read: bit7 BUSY, bit0 ERR (unknown command)
GDATA       = 0xFF27             # read: IDENT record stream, else the last POINT result
GPARM       = 0xFF28             # scalar argument: CIRCLE/ELLIPSE x-radius
GX0H        = 0xFF29             # X0 high byte (write AFTER GX0)
GY0H        = 0xFF2A             # Y0 high byte (write AFTER GY0)
GX1H        = 0xFF2B             # X1 high byte (write AFTER GX1)
GY1H        = 0xFF2C             # Y1 high byte (write AFTER GY1)
GID0        = 0xFF2D             # read: $50 'P' -- card-presence signature
GCOLH       = 0xFF2D             # write: pen HIGH byte (write AFTER GCOL; a GCOL write clears it)
GID1        = 0xFF2E             # read: $47 'G' -- with GID0 spells PG
GPARM2      = 0xFF2F             # ELLIPSE y-radius (GPARM is the x-radius)
MDA         = 0xFF30             # MDU operand a, low byte (write clears the high byte)
MDB         = 0xFF31             # MDU operand b, low byte
MDC         = 0xFF32             # MDU divisor c, low byte
MDQ         = 0xFF33             # read: MDU result (a*b)/c, low byte (poll MDSTAT first)
MDGO        = 0xFF34             # write (any value): start the MDU operation
MDSTAT      = 0xFF35             # read: bit7 BUSY
MDID        = 0xFF36             # read: $4D 'M' -- MDU-presence probe
GESEL       = 0xFF40             # geometry: parameter index (see the list above)
GEVAL       = 0xFF41             # geometry: parameter value, low byte (latched)
GEUP        = 0xFF42             # geometry: upload one edge-list byte, cursor++
GECMD       = 0xFF43             # geometry: 1 rewind cursor / 2 RENDER / 3 FLIP / 4 PGSYNC (draw rejoins display)
GESTAT      = 0xFF44             # read: bit7 BUSY, bit0 ERR (bad count)
GEID        = 0xFF45             # read: $45 'E' -- geometry-engine presence probe
GEVALH      = 0xFF4A             # geometry: value high byte -- commits reg[GESEL], GESEL++
MDAH        = 0xFF39             # MDU operand a, high byte (write AFTER MDA)
MDBH        = 0xFF3A             # MDU operand b, high byte
MDCH        = 0xFF3B             # MDU divisor c, high byte
MDQH        = 0xFF3C             # read: MDU result, high byte

# BIOS / FS scratch ($6000-$60FF)
LBUF        = 0x6000             # input line buffer
ADDRL       = 0x6040             # parsed address
ADDRH       = 0x6041
HEXL        = 0x6042             # hex accumulator
HEXH        = 0x6043
LBA         = 0x6047             # current LBA, byte 0 (bits 7:0)
LBA1        = 0x6048             # LBA byte 1 (bits 15:8)  — 0 after CFINIT unless set
LBA2        = 0x6049             # LBA byte 2 (bits 23:16) — 0 after CFINIT unless set
FNAME       = 0x604A             # 12-byte filename (space-padded) — in for both calls
FSRC        = 0x6056             # FCREATE: source address of the file data (2 bytes)
FLEN        = 0x6058             # file length in bytes (3 bytes): FCREATE in, FFIND out
FSAV        = 0x605B             # FCREATE scratch: requested length saved across FFIND (3)
ROLBA       = 0x605E             # next sector LBA to read (3)
ROREM       = 0x6061             # bytes remaining in the file (3)
ROBUF       = 0x6064             # caller's 512-byte sector buffer address (2)
ROPTR       = 0x6066             # read cursor within ROBUF (2)
ROCNT       = 0x6068             # bytes left in ROBUF; 0 -> refill (3)
WOLBA       = 0x606B             # current output sector LBA (3)
WOPOS       = 0x606E             # byte offset within SBUF; 512 -> flush (2)
WOTOT       = 0x6070             # total bytes written (-> FLEN at close) (3)
DIRLBA      = 0x6073             # current directory start LBA, low byte (16-bit: +DIRLBA1)
DIRN        = 0x6074             # current directory sector count (1)
FFLAG       = 0x6075             # flag of the entry FSCAN matched (file $01 / dir $02)
RPATH       = 0x6076             # FRESOLVE path cursor (2)
DILBA       = 0x6078             # iteration: current directory sector LBA (1)
DICNT       = 0x6079             # iteration: sectors remaining (1)
DIIDX       = 0x607A             # iteration: entry index within the sector (0..15)
FLAREM      = 0x607B             # FLOADAT remaining-bytes counter (CFRDSEC clobbers TMP) (3)
DIBUFH      = 0x607E             # FNEXT directory-buffer page (high byte; low byte 0).
DILBA1      = 0x607F             # FNEXT iteration sector LBA, high byte
DIRLBA1     = 0x6080             # current directory start LBA, high byte (pairs DIRLBA)
FCDH        = 0x6081             # FCREATE directory-sector scan cursor, high byte (HEXL)
DRVSEL      = 0x6082             # current CF drive for sector I/O (0/1); ORed into CFHEAD
CFTOL       = 0x6083             # CF bounded-wait timeout counter, low byte
CFTOH       = 0x6084             # CF bounded-wait timeout counter, high byte
ROSDRV      = 0x6085             # read-stream drive (captured by FOPEN, re-asserted by FG_FILL)
WOSDRV      = 0x6086             # write-stream drive (captured by FWOPEN, re-asserted by FW_FLUSH)
CFIMASK     = 0x6087             # bit N set = drive N has been CFINIT'd this session
REMW        = 0x6088             # FCOM_CORE ceil(FLEN/512): 24-bit remaining counter (3)
CNTW        = 0x608B             # FCOM_CORE sector count, 16-bit (files may span >255 sectors)

# shared sector buffer
SBUF        = 0x6100             # sector buffer

# hardware stack
STKTOP      = 0xFEFF

# BIOS / FS scratch ($6000-$60FF)
ROSTAT      = 0x605E             # read-stream state base (ROLBA..ROCNT, 11 bytes)

# OS scratch ($6300-$69FF)
LINEBUF     = 0x6300             # shell input line (64 bytes)
CMDBUF      = 0x6340             # parsed command word (16 bytes)
NAMEBUF     = 0x6350             # 12-byte filename (search key / DIR scratch)
ECNT        = 0x6363             # entries-left-in-sector counter
FLAGS       = 0x6364             # current entry flag byte
MATCH       = 0x6365             # 1 = name matched / strings equal
LENLO       = 0x6366             # entry length, low 16 bits
LENHI       = 0x6367
STARTLO     = 0x6368             # entry start LBA (low byte)
LOADLO      = 0x6369             # entry load address
LOADHI      = 0x636A
EXECLO      = 0x636B             # entry exec address
EXECHI      = 0x636C
DLBA        = 0x636D             # directory sector being scanned
SECCNT      = 0x636E             # sectors left to transfer
CURLBA      = 0x636F             # current data LBA
ENTPL       = 0x6370             # pointer to a directory entry (in SBUF):
ENTPH       = 0x6371             # flag byte for DEL, entry start for SAVE
ARGPL       = 0x6372             # saved arg position in LINEBUF
ARGPH       = 0x6373
HXLO        = 0x6374             # GETHEX result
HXHI        = 0x6375
DIGIT       = 0x6376             # HEXVAL digit value
SHCNT       = 0x6377             # shift counter
SVSTLO      = 0x6378             # SAVE source start address
SVSTHI      = 0x6379
FREELO      = 0x637A             # boot-block free pointer (next data LBA)
FREEHI      = 0x637B
SRCLO       = 0x637C             # running source pointer during the copy
SRCHI       = 0x637D
REM         = 0x637E             # sectors remaining in the SAVE write loop
NF          = 0x6380             # running next-free LBA
PFOUND      = 0x6381             # 1 if this pass found an unpacked extent
MINSTRT     = 0x6382             # smallest start LBA >= NF this pass
MINSEC      = 0x6383             # that extent's sector count
MINPL       = 0x6384             # pointer to that entry's start-LBA field (in SBUF)
MINPH       = 0x6385
MINDL       = 0x6386             # that entry's directory sector LBA
ESTART      = 0x6387             # current entry start LBA (low byte)
SRCL        = 0x6388             # copy source LBA
DSTL        = 0x6389             # copy dest LBA
CPYN        = 0x638A             # sectors left to copy
CANDL       = 0x638B             # current entry's start-field pointer
CANDH       = 0x638C
ROOTN       = 0x638D             # root directory sector count (4)
DATABASE    = 0x638E             # first data LBA (37)
CWDL        = 0x638F             # current directory: start LBA
CWDN        = 0x6390             # sector count
SDIRL       = 0x6391             # directory being scanned this op (start LBA)
SDIRN       = 0x6392             # sector count
SCNT        = 0x6393             # sectors-left counter while scanning a directory
LSL         = 0x6394             # SETPATH: pointer to the last '/' in CWDPATH
LSH         = 0x6395
PATHL       = 0x6396             # saved path cursor across DESCEND (FINDENT clobbers P2)
PATHH       = 0x6397
NEWLBA      = 0x6398             # MKDIR: LBA of the new directory extent
PSL         = 0x6399             # MKDIR: parent dir start LBA / sector count
PSN         = 0x639A
EFLAG       = 0x639B             # flag byte WRENT stamps (F_FILE for SAVE, F_DIR for MKDIR)
RMDL        = 0x639C             # RMDIR: parent directory sector holding the entry
CDST        = 0x639D             # current directory: start LBA / sectors / entry index
CDSC        = 0x639E
CIDX        = 0x639F
REDIRF      = 0x63A0             # 0 = console, 1 = capturing to RBUF
RCH         = 0x63A1             # OUTCH: byte being emitted
RS2L        = 0x63A2             # OUTCH: saved caller P2
RS2H        = 0x63A3
RPTRL       = 0x63A4             # OUTCH: next free byte in the capture buffer
RPTRH       = 0x63A5
RHX         = 0x63A6             # OPHEX8 scratch
REDNAME     = 0x63A7             # redirect target filename (null-terminated, <=48): $63A7..$63D6
FNDIR       = 0x63D7             # directories counted
FNFIL       = 0x63D8             # files counted
FNDEL       = 0x63D9             # deleted slots counted
FMAXE       = 0x63DA             # highest extent end LBA seen (data area only)
FUSED       = 0x63DB             # data sectors occupied by live extents
FERR        = 0x63DC             # problems found (0 = clean)
FCHILD      = 0x63DD             # CHKDD: directory whose '..' is being checked
FEXP        = 0x63DE             # CHKDD: expected parent LBA

# TPA (transient programs)
RBUF        = 0x6A00             # capture buffer = the TPA (free during a built-in cmd)

# OS scratch ($6300-$69FF)
TSP         = 0x63E0             # tree stack depth (0 = at root level)
TI          = 0x63E1             # scratch loop counter for the frame stack
LENHI2      = 0x63E2             # entry length, bits 16..23 (the BIOS FLEN 3rd byte)
SECCH       = 0x63E3             # SECCOUNT sector-count high byte (files >255 sectors)
MINSECH     = 0x63E4             # PACK: chosen extent's sector count, high byte
CPYNH       = 0x63E5             # PK2MOVE: sectors-to-copy counter, high byte
TFRAME      = 0x64B7             # 8 frames x 4 bytes (dst_lo,dst_hi,dsc,idx): $64B7..$64D6
PPSEC       = 0x63FA             # chosen extent's parent-entry: dir sector LBA / slot
PPSLOT      = 0x63FB
CANDSEC     = 0x63FC             # candidate entry's location during the find walk
CANDSLOT    = 0x63FD
PARST       = 0x63FE             # PK2FIX: parent directory start LBA (for '..')
CWDPATH     = 0x6400             # textual CWD path for the prompt (up to 48 bytes)
INMODE      = 0x6430             # SYS_GETC source: 0 = console, 1 = the read stream
INARM       = 0x6431             # shell armed a '< file' for the next RUN
INNAME      = 0x6432             # '< file' name (null-terminated, <=48): $6432..$6461
PIPEF       = 0x6462             # pipe stage: 0 none, 1 left ran, 2 right ran
PIPEBUF     = 0x6463             # saved right-hand command of a 'cmd | cmd' ($6463..$64A2)
CWDLH       = 0x64A3             # CWDL high byte (current working directory start LBA)
SDIRLH      = 0x64A4             # SDIRL high byte (directory being scanned this op)
STARTHI     = 0x64A5             # STARTLO high byte (entry start LBA from FINDENT)
DLBAH       = 0x64A6             # DLBA high byte (directory-sector scan cursor)
NEWLBAH     = 0x64A7             # NEWLBA high byte (MKDIR new extent)
PSLH        = 0x64A8             # PSL high byte (MKDIR parent extent)
PARSTH      = 0x64A9             # PARST high byte (PACK '..' parent fix)
RMDLH       = 0x64AA             # RMDL high byte (RMDIR parent sector)
CURLBAH     = 0x64AB             # CURLBA high byte (SAVE data-write LBA, 16-bit)
NFH         = 0x64AC             # NF high byte (PACK next-free target)
MINSTRTH    = 0x64AD             # MINSTRT high byte (smallest start LBA this pass)
CDSTH       = 0x64AE             # CDST high byte (current directory in the walk)
CANDSECH    = 0x64AF             # CANDSEC high byte (candidate entry's dir sector)
PPSECH      = 0x64B0             # PPSEC high byte (chosen extent's parent-entry sector)
SRCH        = 0x64B1             # SRCL high byte (PK2MOVE copy source)
DSTH        = 0x64B2             # DSTL high byte (PK2MOVE copy dest)
FCHILDH     = 0x64B3             # FCHILD high byte (CHKDD child dir)
FEXPH       = 0x64B4             # FEXP high byte (CHKDD expected parent)
FMAXEH      = 0x64B5             # FMAXE high byte (FSCK highest extent end)
FUSEDH      = 0x64B6             # FUSED high byte (FSCK live data sectors)
REDAPP      = 0x64D7             # >> append redirect: 1 = prepend the existing file
APHAVE      = 0x64D8             # >> : 1 = an existing file to prepend was found
APLBA       = 0x64D9             # >> : old file's start LBA (2 bytes)
APREM       = 0x64DB             # >> : old file bytes left to copy (2 bytes)
APCHK       = 0x64DD             # >> : bytes to emit from the current sector (2 bytes)
SCRIPTM     = 0x64E0             # 1 = the shell is running lines from a `sh` script
SCRSAVE     = 0x64E1             # saved script read-stream state (ROSTATE 13 + ROSDRV = 14: $64E1..$64EE)
SCRCNT      = 0x64EF             # byte counter for SAVESCR/RESTSCR (1)
APBUF       = 0x6800             # >> prepend sector buffer (512B, below the TPA); also the
IBUF        = 0x6500             # 512-byte buffer for the stdin read stream
PATHBUF     = 0x6700             # search path, ';'-separated dirs; default '/BIN' ($6700..$673F)
RUNPATH     = 0x6740             # scratch: candidate program path built during a lookup ($6740..$679F)
RUNSKIP     = 0x67A0             # DORUN: 1 = skip the program-name word for the arg pointer
PSCANL      = 0x67A1             # PATH search cursor into PATHBUF (low)
PSCANH      = 0x67A2             # PATH search cursor into PATHBUF (high)
GPLF        = 0x67A3             # SYS_GETC console: 1 = a LF is pending after a CR keypress
CURDRIVE    = 0x67A4             # derived: 1 if the CWD is under /d1 (drive 1), else 0
DRVINIT     = 0x67A5             # bitmask: bit N set = drive N has been CFINIT'd this session
MPSAV       = 0x67A6             # MNTPFX: saved P2 (2 bytes) while sniffing a 'd1' prefix

# shell history
HISTST      = 0x608E             # history ring: index where the next entry is written (0..HISTN-1)
HISTCT      = 0x608F             # history ring: number of stored entries (0..HISTN)
HISTNV      = 0x6090             # history ring: recall cursor (0 = not navigating; N = N lines back)
HISTRING    = 0x5800             # history ring buffer base: HISTN x HISTLEN bytes ($5800..$5FFF)

# shell completion
CMPPFX      = 0x5700             # tab-complete: leaf prefix being completed (NUL-term)
CMPLCP      = 0x5740             # tab-complete: longest common prefix of the matches (NUL-term)
CMPDIR      = 0x5760             # tab-complete: directory-part path string, for CDPATH (NUL-term)
CMPPL       = 0x6091             # tab-complete: length of the typed leaf prefix
CMPCNT      = 0x6092             # tab-complete: number of matches (saturates at 255)
CMPFW       = 0x6093             # tab-complete: 1 = completing the command word (first word)
CMPTABF     = 0x6094             # tab-complete: 1 = the previous key was a no-progress Tab
CMPISD      = 0x6095             # tab-complete: 1 = the sole match is a directory
CMPLM       = 0x6096             # tab-complete: 1 = scan in list mode (print matches)
CMPDL       = 0x6097             # tab-complete: target directory start LBA, low byte
CMPDLH      = 0x6098             # tab-complete: target directory start LBA, high byte
CMPDN       = 0x6099             # tab-complete: target directory sector count
CMPCUR      = 0x609A             # tab-complete: saved line length (cursor) across the scan
CMPSAV      = 0x609B             # tab-complete: saved SBUF entry cursor across a candidate (2)
CMPWLB      = 0x609D             # tab-complete: directory-walk running sector LBA (2)
CMPWSC      = 0x609F             # tab-complete: directory-walk sectors remaining
CMPIX       = 0x60A0             # tab-complete: KWTAB index during the built-in scan

# console tty state
TTYRAW      = 0x60A1             # 0 = expand a bare LF to CR LF on console output; nonzero = pass bytes through untouched (for binary over the serial link, like stty raw)
TTYLST      = 0x60A2             # last byte PUTC transmitted, so an LF that already follows a CR is not doubled
TTYCH       = 0x60A3             # PUTC's saved character (PUTC must preserve A)
