/* memmap.h - GENERATED by generators/gen_memmap.py. Do not edit. */
#ifndef P8X_MEMMAP_H
#define P8X_MEMMAP_H


/* memory-region anchors */
#define RAMBASE     0x2000       /* first RAM address (OS + scratch + TPA live here) */
#define IOBASE      0xFF00       /* memory-mapped I/O page */
#define ROMSIZE     0x2000       /* 8K firmware ROM $0000-$1FFF */
#define RAMSIZE     0xDF00       /* RAM span $2000-$FEFF (IOBASE-RAMBASE) */
#define OSORG       0x2000       /* OS load/link address (= RAMBASE) */
#define TPABASE     0x6A00       /* transient program area base (RUNnable programs load here) */
#define CSTACKTOP   0xF800       /* compiler C-stack top (grows down; p8cc __csp init) */
#define WMBASE      0xD800       /* resident window-manager kernel base (GUI apps: TPA $6A00..WMBASE, CSTACKTOP=WMBASE) */

/* I/O ports ($FF00-$FFFF) */
#define ACIAS       0xFF04       /* ACIA status (rd) / control (wr) */
#define ACIAD       0xFF05       /* ACIA data */
#define CFDATA      0xFF10       /* CF task file */
#define CFFEAT      0xFF11
#define CFSCNT      0xFF12
#define CFLBA0      0xFF13
#define CFLBA1      0xFF14
#define CFLBA2      0xFF15
#define CFHEAD      0xFF16       /* $E0 = LBA mode, drive 0 */
#define CFCMD       0xFF17       /* command (wr) / status (rd) */
#define CFSTAT      0xFF17
#define MDA         0xFF30       /* MDU operand a, low byte (write clears the high byte) */
#define MDB         0xFF31       /* MDU operand b, low byte */
#define MDC         0xFF32       /* MDU divisor c, low byte */
#define MDQ         0xFF33       /* read: MDU result (a*b)/c, low byte (poll MDSTAT first) */
#define MDGO        0xFF34       /* write (any value): start the MDU operation */
#define MDSTAT      0xFF35       /* read: bit7 BUSY */
#define MDID        0xFF36       /* read: $4D 'M' -- MDU-presence probe */
#define GLDATA      0xFF50       /* GL: write one command-stream byte into the FIFO */
#define GLSTAT      0xFF51       /* read: bit7 FIFO full, bit6 busy, bit1 error pending, bit0 read-back pending */
#define GLRB        0xFF52       /* read: pop one read-back FIFO byte */
#define GLERR       0xFF53       /* read: pop one error FIFO byte (0 = empty) */
#define GLID        0xFF54       /* read: $47 'G' -- graphics-language presence probe */
#define MDAH        0xFF39       /* MDU operand a, high byte (write AFTER MDA) */
#define MDBH        0xFF3A       /* MDU operand b, high byte */
#define MDCH        0xFF3B       /* MDU divisor c, high byte */
#define MDQH        0xFF3C       /* read: MDU result, high byte */

/* BIOS / FS scratch ($6000-$60FF) */
#define LBUF        0x6000       /* input line buffer */
#define ADDRL       0x6040       /* parsed address */
#define ADDRH       0x6041
#define HEXL        0x6042       /* hex accumulator */
#define HEXH        0x6043
#define LBA         0x6047       /* current LBA, byte 0 (bits 7:0) */
#define LBA1        0x6048       /* LBA byte 1 (bits 15:8)  — 0 after CFINIT unless set */
#define LBA2        0x6049       /* LBA byte 2 (bits 23:16) — 0 after CFINIT unless set */
#define FNAME       0x604A       /* 12-byte filename (space-padded) — in for both calls */
#define FSRC        0x6056       /* FCREATE: source address of the file data (2 bytes) */
#define FLEN        0x6058       /* file length in bytes (3 bytes): FCREATE in, FFIND out */
#define FSAV        0x605B       /* FCREATE scratch: requested length saved across FFIND (3) */
#define ROLBA       0x605E       /* next sector LBA to read (3) */
#define ROREM       0x6061       /* bytes remaining in the file (3) */
#define ROBUF       0x6064       /* caller's 512-byte sector buffer address (2) */
#define ROPTR       0x6066       /* read cursor within ROBUF (2) */
#define ROCNT       0x6068       /* bytes left in ROBUF; 0 -> refill (3) */
#define WOLBA       0x606B       /* current output sector LBA (3) */
#define WOPOS       0x606E       /* byte offset within SBUF; 512 -> flush (2) */
#define WOTOT       0x6070       /* total bytes written (-> FLEN at close) (3) */
#define DIRLBA      0x6073       /* current directory start LBA, low byte (16-bit: +DIRLBA1) */
#define DIRN        0x6074       /* current directory sector count (1) */
#define FFLAG       0x6075       /* flag of the entry FSCAN matched (file $01 / dir $02) */
#define RPATH       0x6076       /* FRESOLVE path cursor (2) */
#define DILBA       0x6078       /* iteration: current directory sector LBA (1) */
#define DICNT       0x6079       /* iteration: sectors remaining (1) */
#define DIIDX       0x607A       /* iteration: entry index within the sector (0..15) */
#define FLAREM      0x607B       /* FLOADAT remaining-bytes counter (CFRDSEC clobbers TMP) (3) */
#define DIBUFH      0x607E       /* FNEXT directory-buffer page (high byte; low byte 0). */
#define DILBA1      0x607F       /* FNEXT iteration sector LBA, high byte */
#define DIRLBA1     0x6080       /* current directory start LBA, high byte (pairs DIRLBA) */
#define FCDH        0x6081       /* FCREATE directory-sector scan cursor, high byte (HEXL) */
#define DRVSEL      0x6082       /* current CF drive for sector I/O (0/1); ORed into CFHEAD */
#define CFTOL       0x6083       /* CF bounded-wait timeout counter, low byte */
#define CFTOH       0x6084       /* CF bounded-wait timeout counter, high byte */
#define ROSDRV      0x6085       /* read-stream drive (captured by FOPEN, re-asserted by FG_FILL) */
#define WOSDRV      0x6086       /* write-stream drive (captured by FWOPEN, re-asserted by FW_FLUSH) */
#define CFIMASK     0x6087       /* bit N set = drive N has been CFINIT'd this session */
#define REMW        0x6088       /* FCOM_CORE ceil(FLEN/512): 24-bit remaining counter (3) */
#define CNTW        0x608B       /* FCOM_CORE sector count, 16-bit (files may span >255 sectors) */

/* shared sector buffer */
#define SBUF        0x6100       /* sector buffer */

/* hardware stack */
#define STKTOP      0xFEFF

/* BIOS / FS scratch ($6000-$60FF) */
#define ROSTAT      0x605E       /* read-stream state base (ROLBA..ROCNT, 11 bytes) */

/* OS scratch ($6300-$69FF) */
#define LINEBUF     0x6300       /* shell input line (64 bytes) */
#define CMDBUF      0x6340       /* parsed command word (16 bytes) */
#define NAMEBUF     0x6350       /* 12-byte filename (search key / DIR scratch) */
#define ECNT        0x6363       /* entries-left-in-sector counter */
#define FLAGS       0x6364       /* current entry flag byte */
#define MATCH       0x6365       /* 1 = name matched / strings equal */
#define LENLO       0x6366       /* entry length, low 16 bits */
#define LENHI       0x6367
#define STARTLO     0x6368       /* entry start LBA (low byte) */
#define LOADLO      0x6369       /* entry load address */
#define LOADHI      0x636A
#define EXECLO      0x636B       /* entry exec address */
#define EXECHI      0x636C
#define DLBA        0x636D       /* directory sector being scanned */
#define SECCNT      0x636E       /* sectors left to transfer */
#define CURLBA      0x636F       /* current data LBA */
#define ENTPL       0x6370       /* pointer to a directory entry (in SBUF): */
#define ENTPH       0x6371       /* flag byte for DEL, entry start for SAVE */
#define ARGPL       0x6372       /* saved arg position in LINEBUF */
#define ARGPH       0x6373
#define HXLO        0x6374       /* GETHEX result */
#define HXHI        0x6375
#define DIGIT       0x6376       /* HEXVAL digit value */
#define SHCNT       0x6377       /* shift counter */
#define SVSTLO      0x6378       /* SAVE source start address */
#define SVSTHI      0x6379
#define FREELO      0x637A       /* boot-block free pointer (next data LBA) */
#define FREEHI      0x637B
#define SRCLO       0x637C       /* running source pointer during the copy */
#define SRCHI       0x637D
#define REM         0x637E       /* sectors remaining in the SAVE write loop */
#define NF          0x6380       /* running next-free LBA */
#define PFOUND      0x6381       /* 1 if this pass found an unpacked extent */
#define MINSTRT     0x6382       /* smallest start LBA >= NF this pass */
#define MINSEC      0x6383       /* that extent's sector count */
#define MINPL       0x6384       /* pointer to that entry's start-LBA field (in SBUF) */
#define MINPH       0x6385
#define MINDL       0x6386       /* that entry's directory sector LBA */
#define ESTART      0x6387       /* current entry start LBA (low byte) */
#define SRCL        0x6388       /* copy source LBA */
#define DSTL        0x6389       /* copy dest LBA */
#define CPYN        0x638A       /* sectors left to copy */
#define CANDL       0x638B       /* current entry's start-field pointer */
#define CANDH       0x638C
#define ROOTN       0x638D       /* root directory sector count (4) */
#define DATABASE    0x638E       /* first data LBA (37) */
#define CWDL        0x638F       /* current directory: start LBA */
#define CWDN        0x6390       /* sector count */
#define SDIRL       0x6391       /* directory being scanned this op (start LBA) */
#define SDIRN       0x6392       /* sector count */
#define SCNT        0x6393       /* sectors-left counter while scanning a directory */
#define LSL         0x6394       /* SETPATH: pointer to the last '/' in CWDPATH */
#define LSH         0x6395
#define PATHL       0x6396       /* saved path cursor across DESCEND (FINDENT clobbers P2) */
#define PATHH       0x6397
#define NEWLBA      0x6398       /* MKDIR: LBA of the new directory extent */
#define PSL         0x6399       /* MKDIR: parent dir start LBA / sector count */
#define PSN         0x639A
#define EFLAG       0x639B       /* flag byte WRENT stamps (F_FILE for SAVE, F_DIR for MKDIR) */
#define RMDL        0x639C       /* RMDIR: parent directory sector holding the entry */
#define CDST        0x639D       /* current directory: start LBA / sectors / entry index */
#define CDSC        0x639E
#define CIDX        0x639F
#define REDIRF      0x63A0       /* 0 = console, 1 = capturing to RBUF */
#define RCH         0x63A1       /* OUTCH: byte being emitted */
#define RS2L        0x63A2       /* OUTCH: saved caller P2 */
#define RS2H        0x63A3
#define RPTRL       0x63A4       /* OUTCH: next free byte in the capture buffer */
#define RPTRH       0x63A5
#define RHX         0x63A6       /* OPHEX8 scratch */
#define REDNAME     0x63A7       /* redirect target filename (null-terminated, <=48): $63A7..$63D6 */
#define FNDIR       0x63D7       /* directories counted */
#define FNFIL       0x63D8       /* files counted */
#define FNDEL       0x63D9       /* deleted slots counted */
#define FMAXE       0x63DA       /* highest extent end LBA seen (data area only) */
#define FUSED       0x63DB       /* data sectors occupied by live extents */
#define FERR        0x63DC       /* problems found (0 = clean) */
#define FCHILD      0x63DD       /* CHKDD: directory whose '..' is being checked */
#define FEXP        0x63DE       /* CHKDD: expected parent LBA */

/* TPA (transient programs) */
#define RBUF        0x6A00       /* capture buffer = the TPA (free during a built-in cmd) */

/* OS scratch ($6300-$69FF) */
#define TSP         0x63E0       /* tree stack depth (0 = at root level) */
#define TI          0x63E1       /* scratch loop counter for the frame stack */
#define LENHI2      0x63E2       /* entry length, bits 16..23 (the BIOS FLEN 3rd byte) */
#define SECCH       0x63E3       /* SECCOUNT sector-count high byte (files >255 sectors) */
#define MINSECH     0x63E4       /* PACK: chosen extent's sector count, high byte */
#define CPYNH       0x63E5       /* PK2MOVE: sectors-to-copy counter, high byte */
#define TFRAME      0x64B7       /* 8 frames x 4 bytes (dst_lo,dst_hi,dsc,idx): $64B7..$64D6 */
#define PPSEC       0x63FA       /* chosen extent's parent-entry: dir sector LBA / slot */
#define PPSLOT      0x63FB
#define CANDSEC     0x63FC       /* candidate entry's location during the find walk */
#define CANDSLOT    0x63FD
#define PARST       0x63FE       /* PK2FIX: parent directory start LBA (for '..') */
#define CWDPATH     0x6400       /* textual CWD path for the prompt (up to 48 bytes) */
#define INMODE      0x6430       /* SYS_GETC source: 0 = console, 1 = the read stream */
#define INARM       0x6431       /* shell armed a '< file' for the next RUN */
#define INNAME      0x6432       /* '< file' name (null-terminated, <=48): $6432..$6461 */
#define PIPEF       0x6462       /* pipe stage: 0 none, 1 left ran, 2 right ran */
#define PIPEBUF     0x6463       /* saved right-hand command of a 'cmd | cmd' ($6463..$64A2) */
#define CWDLH       0x64A3       /* CWDL high byte (current working directory start LBA) */
#define SDIRLH      0x64A4       /* SDIRL high byte (directory being scanned this op) */
#define STARTHI     0x64A5       /* STARTLO high byte (entry start LBA from FINDENT) */
#define DLBAH       0x64A6       /* DLBA high byte (directory-sector scan cursor) */
#define NEWLBAH     0x64A7       /* NEWLBA high byte (MKDIR new extent) */
#define PSLH        0x64A8       /* PSL high byte (MKDIR parent extent) */
#define PARSTH      0x64A9       /* PARST high byte (PACK '..' parent fix) */
#define RMDLH       0x64AA       /* RMDL high byte (RMDIR parent sector) */
#define CURLBAH     0x64AB       /* CURLBA high byte (SAVE data-write LBA, 16-bit) */
#define NFH         0x64AC       /* NF high byte (PACK next-free target) */
#define MINSTRTH    0x64AD       /* MINSTRT high byte (smallest start LBA this pass) */
#define CDSTH       0x64AE       /* CDST high byte (current directory in the walk) */
#define CANDSECH    0x64AF       /* CANDSEC high byte (candidate entry's dir sector) */
#define PPSECH      0x64B0       /* PPSEC high byte (chosen extent's parent-entry sector) */
#define SRCH        0x64B1       /* SRCL high byte (PK2MOVE copy source) */
#define DSTH        0x64B2       /* DSTL high byte (PK2MOVE copy dest) */
#define FCHILDH     0x64B3       /* FCHILD high byte (CHKDD child dir) */
#define FEXPH       0x64B4       /* FEXP high byte (CHKDD expected parent) */
#define FMAXEH      0x64B5       /* FMAXE high byte (FSCK highest extent end) */
#define FUSEDH      0x64B6       /* FUSED high byte (FSCK live data sectors) */
#define REDAPP      0x64D7       /* >> append redirect: 1 = prepend the existing file */
#define APHAVE      0x64D8       /* >> : 1 = an existing file to prepend was found */
#define APLBA       0x64D9       /* >> : old file's start LBA (2 bytes) */
#define APREM       0x64DB       /* >> : old file bytes left to copy (2 bytes) */
#define APCHK       0x64DD       /* >> : bytes to emit from the current sector (2 bytes) */
#define SCRIPTM     0x64E0       /* 1 = the shell is running lines from a `sh` script */
#define SCRSAVE     0x64E1       /* saved script read-stream state (ROSTATE 13 + ROSDRV = 14: $64E1..$64EE) */
#define SCRCNT      0x64EF       /* byte counter for SAVESCR/RESTSCR (1) */
#define APBUF       0x6800       /* >> prepend sector buffer (512B, below the TPA); also the */
#define IBUF        0x6500       /* 512-byte buffer for the stdin read stream */
#define PATHBUF     0x6700       /* search path, ';'-separated dirs; default '/BIN' ($6700..$673F) */
#define RUNPATH     0x6740       /* scratch: candidate program path built during a lookup ($6740..$679F) */
#define RUNSKIP     0x67A0       /* DORUN: 1 = skip the program-name word for the arg pointer */
#define PSCANL      0x67A1       /* PATH search cursor into PATHBUF (low) */
#define PSCANH      0x67A2       /* PATH search cursor into PATHBUF (high) */
#define GPLF        0x67A3       /* SYS_GETC console: 1 = a LF is pending after a CR keypress */
#define CURDRIVE    0x67A4       /* derived: 1 if the CWD is under /d1 (drive 1), else 0 */
#define DRVINIT     0x67A5       /* bitmask: bit N set = drive N has been CFINIT'd this session */
#define MPSAV       0x67A6       /* MNTPFX: saved P2 (2 bytes) while sniffing a 'd1' prefix */

/* shell history */
#define HISTST      0x608E       /* history ring: index where the next entry is written (0..HISTN-1) */
#define HISTCT      0x608F       /* history ring: number of stored entries (0..HISTN) */
#define HISTNV      0x6090       /* history ring: recall cursor (0 = not navigating; N = N lines back) */
#define HISTRING    0x5800       /* history ring buffer base: HISTN x HISTLEN bytes ($5800..$5FFF) */

/* shell completion */
#define CMPPFX      0x5700       /* tab-complete: leaf prefix being completed (NUL-term) */
#define CMPLCP      0x5740       /* tab-complete: longest common prefix of the matches (NUL-term) */
#define CMPDIR      0x5760       /* tab-complete: directory-part path string, for CDPATH (NUL-term) */
#define CMPPL       0x6091       /* tab-complete: length of the typed leaf prefix */
#define CMPCNT      0x6092       /* tab-complete: number of matches (saturates at 255) */
#define CMPFW       0x6093       /* tab-complete: 1 = completing the command word (first word) */
#define CMPTABF     0x6094       /* tab-complete: 1 = the previous key was a no-progress Tab */
#define CMPISD      0x6095       /* tab-complete: 1 = the sole match is a directory */
#define CMPLM       0x6096       /* tab-complete: 1 = scan in list mode (print matches) */
#define CMPDL       0x6097       /* tab-complete: target directory start LBA, low byte */
#define CMPDLH      0x6098       /* tab-complete: target directory start LBA, high byte */
#define CMPDN       0x6099       /* tab-complete: target directory sector count */
#define CMPCUR      0x609A       /* tab-complete: saved line length (cursor) across the scan */
#define CMPSAV      0x609B       /* tab-complete: saved SBUF entry cursor across a candidate (2) */
#define CMPWLB      0x609D       /* tab-complete: directory-walk running sector LBA (2) */
#define CMPWSC      0x609F       /* tab-complete: directory-walk sectors remaining */
#define CMPIX       0x60A0       /* tab-complete: KWTAB index during the built-in scan */

/* console tty state */
#define TTYRAW      0x60A1       /* 0 = expand a bare LF to CR LF on console output; nonzero = pass bytes through untouched (for binary over the serial link, like stty raw) */
#define TTYLST      0x60A2       /* last byte PUTC transmitted, so an LF that already follows a CR is not doubled */
#define TTYCH       0x60A3       /* PUTC's saved character (PUTC must preserve A) */

#endif
