# memmap.py - GENERATED by generators/gen_memmap.py. Do not edit.


# memory-region anchors
RAMBASE     = 0x1800             # first RAM address (ROM shrunk 8K->6K 2026-09-14; $1800-$1FFF is a low RAM island)
IOBASE      = 0xFF00             # memory-mapped I/O page
ROMSIZE     = 0x1800             # 6K firmware ROM $0000-$17FF (monitor uses ~5.2K)
RAMSIZE     = 0xE700             # RAM span $1800-$FEFF (IOBASE-RAMBASE)
OSORG       = 0x2000             # OS load/link address (still $2000; the $1800-$1FFF RAM island holds relocated scratch)
TPABASE     = 0x5900             # transient program area base (RUNnable programs load here)
CSTACKTOP   = 0xF800             # compiler C-stack top (grows down; p8cc __csp init)

# I/O ports ($FF00-$FFFF)
ACIAS       = 0xFF04             # ACIA status (rd) / control (wr)
ACIAD       = 0xFF05             # ACIA data
ACIA2S      = 0xFF08             # 2nd ACIA status (rd) / control (wr) -- the Kermit/serial-terminal port
ACIA2D      = 0xFF09             # 2nd ACIA data
CFDATA      = 0xFF10             # CF task file
CFFEAT      = 0xFF11
CFSCNT      = 0xFF12
CFLBA0      = 0xFF13
CFLBA1      = 0xFF14
CFLBA2      = 0xFF15
CFHEAD      = 0xFF16             # $E0 = LBA mode, drive 0
CFCMD       = 0xFF17             # command (wr) / status (rd)
CFSTAT      = 0xFF17
MDA         = 0xFF30             # MDU operand a, low byte (write clears the high byte)
MDB         = 0xFF31             # MDU operand b, low byte
MDC         = 0xFF32             # MDU divisor c, low byte
MDQ         = 0xFF33             # read: MDU result (a*b)/c, low byte (poll MDSTAT first)
MDGO        = 0xFF34             # write (any value): start the MDU operation
MDSTAT      = 0xFF35             # read: bit7 BUSY
MDID        = 0xFF36             # read: $4D 'M' -- MDU-presence probe
GLDATA      = 0xFF50             # GL: write one command-stream byte into the FIFO
GLSTAT      = 0xFF51             # read: bit7 FIFO full, bit6 busy, bit1 error pending, bit0 read-back pending
GLRB        = 0xFF52             # read: pop one read-back FIFO byte
GLERR       = 0xFF53             # read: pop one error FIFO byte (0 = empty)
GLID        = 0xFF54             # read: $47 'G' -- graphics-language presence probe
PSADAT      = 0xFF58             # read: port A (keyboard) byte, ready cleared on read (raw Set-2)
PSAST       = 0xFF59             # port A status: r bit0 ready/bit1 overrun/bit2 parity; w bit0 CLK-low/bit1 DATA-low
PSBDAT      = 0xFF5A             # read: port B (mouse) byte, ready cleared on read
PSBST       = 0xFF5B             # port B status: as PSAST
PSLINE      = 0xFF5C             # read: live line states (bit0 Aclk/bit1 Adat/bit2 Bclk/bit3 Bdat) for the bit-banged transmit
PSID        = 0xFF5E             # read: $4B 'K' -- PS/2-card presence probe (absent floats $FF)
MDAH        = 0xFF39             # MDU operand a, high byte (write AFTER MDA)
MDBH        = 0xFF3A             # MDU operand b, high byte
MDCH        = 0xFF3B             # MDU divisor c, high byte
MDQH        = 0xFF3C             # read: MDU result, high byte

# BIOS / FS scratch (moved to $1F00-$1FFF island)
LBUF        = 0x1F00             # input line buffer
ADDRL       = 0x1F40             # parsed address
ADDRH       = 0x1F41
HEXL        = 0x1F42             # hex accumulator
HEXH        = 0x1F43
LBA         = 0x1F47             # current LBA, byte 0 (bits 7:0)
LBA1        = 0x1F48             # LBA byte 1 (bits 15:8)  — 0 after CFINIT unless set
LBA2        = 0x1F49             # LBA byte 2 (bits 23:16) — 0 after CFINIT unless set
FNAME       = 0x1F4A             # 12-byte filename (space-padded) — in for both calls
FSRC        = 0x1F56             # FCREATE: source address of the file data (2 bytes)
FLEN        = 0x1F58             # file length in bytes (3 bytes): FCREATE in, FFIND out
FSAV        = 0x1F5B             # FCREATE scratch: requested length saved across FFIND (3)
ROLBA       = 0x1F5E             # next sector LBA to read (3)
ROREM       = 0x1F61             # bytes remaining in the file (3)
ROBUF       = 0x1F64             # caller's 512-byte sector buffer address (2)
ROPTR       = 0x1F66             # read cursor within ROBUF (2)
ROCNT       = 0x1F68             # bytes left in ROBUF; 0 -> refill (3)
WOLBA       = 0x1F6B             # current output sector LBA (3)
WOPOS       = 0x1F6E             # byte offset within SBUF; 512 -> flush (2)
WOTOT       = 0x1F70             # total bytes written (-> FLEN at close) (3)
DIRLBA      = 0x1F73             # current directory start LBA, low byte (16-bit: +DIRLBA1)
DIRN        = 0x1F74             # current directory sector count (1)
FFLAG       = 0x1F75             # flag of the entry FSCAN matched (file $01 / dir $02)
RPATH       = 0x1F76             # FRESOLVE path cursor (2)
DILBA       = 0x1F78             # iteration: current directory sector LBA (1)
DICNT       = 0x1F79             # iteration: sectors remaining (1)
DIIDX       = 0x1F7A             # iteration: entry index within the sector (0..15)
FLAREM      = 0x1F7B             # FLOADAT remaining-bytes counter (CFRDSEC clobbers TMP) (3)
DIBUFH      = 0x1F7E             # FNEXT directory-buffer page (high byte; low byte 0).
DILBA1      = 0x1F7F             # FNEXT iteration sector LBA, high byte
DIRLBA1     = 0x1F80             # current directory start LBA, high byte (pairs DIRLBA)
FCDH        = 0x1F81             # FCREATE directory-sector scan cursor, high byte (HEXL)
DRVSEL      = 0x1F82             # current CF drive for sector I/O (0/1); ORed into CFHEAD
CFTOL       = 0x1F83             # CF bounded-wait timeout counter, low byte
CFTOH       = 0x1F84             # CF bounded-wait timeout counter, high byte
ROSDRV      = 0x1F85             # read-stream drive (captured by FOPEN, re-asserted by FG_FILL)
WOSDRV      = 0x1F86             # write-stream drive (captured by FWOPEN, re-asserted by FW_FLUSH)
CFIMASK     = 0x1F87             # bit N set = drive N has been CFINIT'd this session
REMW        = 0x1F88             # FCOM_CORE ceil(FLEN/512): 24-bit remaining counter (3)
CNTW        = 0x1F8B             # FCOM_CORE sector count, 16-bit (files may span >255 sectors)

# shared sector buffer
SBUF        = 0x1D00             # sector buffer

# hardware stack
STKTOP      = 0xFEFF

# BIOS / FS scratch (moved to $1F00-$1FFF island)
ROSTAT      = 0x1F5E             # read-stream state base (ROLBA..ROCNT, 11 bytes)

# OS scratch (top moved to the $1800-$1FFF island)
LINEBUF     = 0x5700             # shell input line (64 bytes)
CMDBUF      = 0x5740             # parsed command word (16 bytes)
NAMEBUF     = 0x5750             # 12-byte filename (search key / DIR scratch)
ECNT        = 0x5763             # entries-left-in-sector counter
FLAGS       = 0x5764             # current entry flag byte
MATCH       = 0x5765             # 1 = name matched / strings equal
LENLO       = 0x5766             # entry length, low 16 bits
LENHI       = 0x5767
STARTLO     = 0x5768             # entry start LBA (low byte)
LOADLO      = 0x5769             # entry load address
LOADHI      = 0x576A
EXECLO      = 0x576B             # entry exec address
EXECHI      = 0x576C
DLBA        = 0x576D             # directory sector being scanned
SECCNT      = 0x576E             # sectors left to transfer
CURLBA      = 0x576F             # current data LBA
ENTPL       = 0x5770             # pointer to a directory entry (in SBUF):
ENTPH       = 0x5771             # flag byte for DEL, entry start for SAVE
ARGPL       = 0x5772             # saved arg position in LINEBUF
ARGPH       = 0x5773
HXLO        = 0x5774             # GETHEX result
HXHI        = 0x5775
DIGIT       = 0x5776             # HEXVAL digit value
SHCNT       = 0x5777             # shift counter
SVSTLO      = 0x5778             # SAVE source start address
SVSTHI      = 0x5779
FREELO      = 0x577A             # boot-block free pointer (next data LBA)
FREEHI      = 0x577B
SRCLO       = 0x577C             # running source pointer during the copy
SRCHI       = 0x577D
REM         = 0x577E             # sectors remaining in the SAVE write loop
NF          = 0x5780             # running next-free LBA
PFOUND      = 0x5781             # 1 if this pass found an unpacked extent
MINSTRT     = 0x5782             # smallest start LBA >= NF this pass
MINSEC      = 0x5783             # that extent's sector count
MINPL       = 0x5784             # pointer to that entry's start-LBA field (in SBUF)
MINPH       = 0x5785
MINDL       = 0x5786             # that entry's directory sector LBA
ESTART      = 0x5787             # current entry start LBA (low byte)
SRCL        = 0x5788             # copy source LBA
DSTL        = 0x5789             # copy dest LBA
CPYN        = 0x578A             # sectors left to copy
CANDL       = 0x578B             # current entry's start-field pointer
CANDH       = 0x578C
ROOTN       = 0x578D             # root directory sector count (4)
DATABASE    = 0x578E             # first data LBA (37)
CWDL        = 0x578F             # current directory: start LBA
CWDN        = 0x5790             # sector count
SDIRL       = 0x5791             # directory being scanned this op (start LBA)
SDIRN       = 0x5792             # sector count
SCNT        = 0x5793             # sectors-left counter while scanning a directory
LSL         = 0x5794             # SETPATH: pointer to the last '/' in CWDPATH
LSH         = 0x5795
PATHL       = 0x5796             # saved path cursor across DESCEND (FINDENT clobbers P2)
PATHH       = 0x5797
NEWLBA      = 0x5798             # MKDIR: LBA of the new directory extent
PSL         = 0x5799             # MKDIR: parent dir start LBA / sector count
PSN         = 0x579A
EFLAG       = 0x579B             # flag byte WRENT stamps (F_FILE for SAVE, F_DIR for MKDIR)
RMDL        = 0x579C             # RMDIR: parent directory sector holding the entry
CDST        = 0x579D             # current directory: start LBA / sectors / entry index
CDSC        = 0x579E
CIDX        = 0x579F
REDIRF      = 0x57A0             # 0 = console, 1 = capturing to RBUF
RCH         = 0x57A1             # OUTCH: byte being emitted
RS2L        = 0x57A2             # OUTCH: saved caller P2
RS2H        = 0x57A3
RPTRL       = 0x57A4             # OUTCH: next free byte in the capture buffer
RPTRH       = 0x57A5
RHX         = 0x57A6             # OPHEX8 scratch
REDNAME     = 0x57A7             # redirect target filename (null-terminated, <=48): $63A7..$63D6
FNDIR       = 0x57D7             # directories counted
FNFIL       = 0x57D8             # files counted
FNDEL       = 0x57D9             # deleted slots counted
FMAXE       = 0x57DA             # highest extent end LBA seen (data area only)
FUSED       = 0x57DB             # data sectors occupied by live extents
FERR        = 0x57DC             # problems found (0 = clean)
FCHILD      = 0x57DD             # CHKDD: directory whose '..' is being checked
FEXP        = 0x57DE             # CHKDD: expected parent LBA

# TPA (transient programs)
RBUF        = 0x5900             # capture buffer = the TPA (free during a built-in cmd)

# OS scratch (top moved to the $1800-$1FFF island)
TSP         = 0x57E0             # tree stack depth (0 = at root level)
TI          = 0x57E1             # scratch loop counter for the frame stack
LENHI2      = 0x57E2             # entry length, bits 16..23 (the BIOS FLEN 3rd byte)
SECCH       = 0x57E3             # SECCOUNT sector-count high byte (files >255 sectors)
MINSECH     = 0x57E4             # PACK: chosen extent's sector count, high byte
CPYNH       = 0x57E5             # PK2MOVE: sectors-to-copy counter, high byte
TFRAME      = 0x58B7             # 8 frames x 4 bytes (dst_lo,dst_hi,dsc,idx): $64B7..$64D6
PPSEC       = 0x57FA             # chosen extent's parent-entry: dir sector LBA / slot
PPSLOT      = 0x57FB
CANDSEC     = 0x57FC             # candidate entry's location during the find walk
CANDSLOT    = 0x57FD
PARST       = 0x57FE             # PK2FIX: parent directory start LBA (for '..')
CWDPATH     = 0x5800             # textual CWD path for the prompt (up to 48 bytes)
INMODE      = 0x5830             # SYS_GETC source: 0 = console, 1 = the read stream
INARM       = 0x5831             # shell armed a '< file' for the next RUN
INNAME      = 0x5832             # '< file' name (null-terminated, <=48): $6432..$6461
PIPEF       = 0x5862             # pipe stage: 0 none, 1 left ran, 2 right ran
PIPEBUF     = 0x5863             # saved right-hand command of a 'cmd | cmd' ($6463..$64A2)
CWDLH       = 0x58A3             # CWDL high byte (current working directory start LBA)
SDIRLH      = 0x58A4             # SDIRL high byte (directory being scanned this op)
STARTHI     = 0x58A5             # STARTLO high byte (entry start LBA from FINDENT)
DLBAH       = 0x58A6             # DLBA high byte (directory-sector scan cursor)
NEWLBAH     = 0x58A7             # NEWLBA high byte (MKDIR new extent)
PSLH        = 0x58A8             # PSL high byte (MKDIR parent extent)
PARSTH      = 0x58A9             # PARST high byte (PACK '..' parent fix)
RMDLH       = 0x58AA             # RMDL high byte (RMDIR parent sector)
CURLBAH     = 0x58AB             # CURLBA high byte (SAVE data-write LBA, 16-bit)
NFH         = 0x58AC             # NF high byte (PACK next-free target)
MINSTRTH    = 0x58AD             # MINSTRT high byte (smallest start LBA this pass)
CDSTH       = 0x58AE             # CDST high byte (current directory in the walk)
CANDSECH    = 0x58AF             # CANDSEC high byte (candidate entry's dir sector)
PPSECH      = 0x58B0             # PPSEC high byte (chosen extent's parent-entry sector)
SRCH        = 0x58B1             # SRCL high byte (PK2MOVE copy source)
DSTH        = 0x58B2             # DSTL high byte (PK2MOVE copy dest)
FCHILDH     = 0x58B3             # FCHILD high byte (CHKDD child dir)
FEXPH       = 0x58B4             # FEXP high byte (CHKDD expected parent)
FMAXEH      = 0x58B5             # FMAXE high byte (FSCK highest extent end)
FUSEDH      = 0x58B6             # FUSED high byte (FSCK live data sectors)
REDAPP      = 0x58D7             # >> append redirect: 1 = prepend the existing file
APHAVE      = 0x58D8             # >> : 1 = an existing file to prepend was found
APLBA       = 0x58D9             # >> : old file's start LBA (2 bytes)
APREM       = 0x58DB             # >> : old file bytes left to copy (2 bytes)
APCHK       = 0x58DD             # >> : bytes to emit from the current sector (2 bytes)
SCRIPTM     = 0x58E0             # 1 = the shell is running lines from a `sh` script
SCRSAVE     = 0x58E1             # saved script read-stream state (ROSTATE 13 + ROSDRV = 14: $64E1..$64EE)
SCRCNT      = 0x58EF             # byte counter for SAVESCR/RESTSCR (1)
APBUF       = 0x1B00             # >> prepend sector buffer (512B, below the TPA); also the
IBUF        = 0x1800             # 512-byte buffer for the stdin read stream
PATHBUF     = 0x1A00             # search path, ';'-separated dirs; default '/BIN' ($6700..$673F)
RUNPATH     = 0x1A40             # scratch: candidate program path built during a lookup ($6740..$679F)
RUNSKIP     = 0x1AA0             # DORUN: 1 = skip the program-name word for the arg pointer
PSCANL      = 0x1AA1             # PATH search cursor into PATHBUF (low)
PSCANH      = 0x1AA2             # PATH search cursor into PATHBUF (high)
GPLF        = 0x1AA3             # SYS_GETC console: 1 = a LF is pending after a CR keypress
CURDRIVE    = 0x1AA4             # derived: 1 if the CWD is under /d1 (drive 1), else 0
DRVINIT     = 0x1AA5             # bitmask: bit N set = drive N has been CFINIT'd this session
MPSAV       = 0x1AA6             # MNTPFX: saved P2 (2 bytes) while sniffing a 'd1' prefix

# shell history
HISTST      = 0x1F8E             # history ring: index where the next entry is written (0..HISTN-1)
HISTCT      = 0x1F8F             # history ring: number of stored entries (0..HISTN)
HISTNV      = 0x1F90             # history ring: recall cursor (0 = not navigating; N = N lines back)
HISTRING    = 0xF800             # history ring buffer base: HISTN x HISTLEN bytes ($F800..$F9FF, the free 512 B above CSTACKTOP; $FA00 = glob page, $FC00 = RDBUF, $FE00 = stack)

# shell completion
CMPPFX      = 0x1B00             # tab-complete: leaf prefix being completed (NUL-term, 64; aliases APBUF)
CMPLCP      = 0x1B40             # tab-complete: longest common prefix of the matches (NUL-term, 16; aliases APBUF)
CMPDIR      = 0x1B50             # tab-complete: directory-part path string, for CDPATH (NUL-term, 64; aliases APBUF)
CMPPL       = 0x1F91             # tab-complete: length of the typed leaf prefix
CMPCNT      = 0x1F92             # tab-complete: number of matches (saturates at 255)
CMPFW       = 0x1F93             # tab-complete: 1 = completing the command word (first word)
CMPTABF     = 0x1F94             # tab-complete: 1 = the previous key was a no-progress Tab
CMPISD      = 0x1F95             # tab-complete: 1 = the sole match is a directory
CMPLM       = 0x1F96             # tab-complete: 1 = scan in list mode (print matches)
CMPDL       = 0x1F97             # tab-complete: target directory start LBA, low byte
CMPDLH      = 0x1F98             # tab-complete: target directory start LBA, high byte
CMPDN       = 0x1F99             # tab-complete: target directory sector count
CMPCUR      = 0x1F9A             # tab-complete: saved line length (cursor) across the scan
CMPSAV      = 0x1F9B             # tab-complete: saved SBUF entry cursor across a candidate (2)
CMPWLB      = 0x1F9D             # tab-complete: directory-walk running sector LBA (2)
CMPWSC      = 0x1F9F             # tab-complete: directory-walk sectors remaining
CMPIX       = 0x1FA0             # tab-complete: KWTAB index during the built-in scan

# console tty state
TTYRAW      = 0x1FA1             # 0 = expand a bare LF to CR LF on console output; nonzero = pass bytes through untouched (for binary over the serial link, like stty raw)
TTYLST      = 0x1FA2             # last byte PUTC transmitted, so an LF that already follows a CR is not doubled
TTYCH       = 0x1FA3             # PUTC's saved character (PUTC must preserve A)

# graphics presence
GFXPRES     = 0x1FA4             # 1 = GL card fitted (screen is the display); 0 = headless serial console

# glass tty
GTCOL       = 0x1FA5             # glass TTY cursor column (0..GTCOLS-1)
GTROW       = 0x1FA6             # glass TTY cursor row (0..GTROWS-1)
GTSUSP      = 0x1FA7             # nonzero = glass TTY suspended (a full-screen GL app owns the screen; CONOUT is serial-only)
GCONEN      = 0x1FAF             # 1 = glass TTY console ENABLED (CONOUT mirrors to the GL screen); 0 = off (serial-only, the default -- `screen on` enables it)
GTXL        = 0x1FA8             # glass TTY cursor pixel x, low byte (0..474, step 6)
GTXH        = 0x1FA9             # glass TTY cursor pixel x, high byte
GTYL        = 0x1FAA             # glass TTY text-baseline pixel y (window, y-up), low byte
GTYH        = 0x1FAB             # glass TTY text-baseline pixel y, high byte
GTCH        = 0x1FAC             # glass TTY: the byte currently being drawn
GTTMP       = 0x1FAD             # glass TTY: FIFO-push scratch (holds the byte across the backpressure wait)
GTCNT       = 0x1FAE             # glass TTY: table-stream byte counter
