// tb_geom.v -- the stage-8b geometry engine against the SAME host reference
// that pins the emulator and the library: expected line coordinates below
// were generated by the c_g3d_test pipeline replica (see STAGE8B-DESIGN.md),
// so all three implementations answer to one oracle.
//
// The engine talks to a register-level gfx STUB (records the erase, the pen
// writes and every LINE's coordinates; GSTAT holds busy a few cycles per
// command to exercise the engine's polling) and an SDRAM stub on the g port
// (latency on both acks, so the FIFO and req/ready handshakes are real).
//
// Checks: upload lands intact; the erase targets the viewport with pen 0;
// the pen is white for lines; 7 identity-matrix edges produce exactly the 5
// expected lines (near clip, CS clip both axes, drop, reject); 3 cube-matrix
// edges produce the transformed lines; flags=3 holds busy until frame_tick
// and then swaps the pages by the display<=draw, draw<=~draw rule; GECMD 3
// flips manually.
//
//   iverilog -g2012 -o tbgm tb_geom.v ../../rtl/p8x_geom.v ../../rtl/mdu_core.v
//   ./tbgm
`timescale 1ns/1ps

module tb;
  reg clk = 0, rst = 1;
  always #5 clk = ~clk;

  reg        sel = 0, wr = 0;
  reg  [3:0] a = 0;
  reg  [7:0] wdata = 0;
  wire [7:0] rdata;

  wire        gm_own, gm_wr;
  wire [3:0]  gm_a;
  wire [7:0]  gm_wdata;
  reg  [7:0]  gm_rdata;
  wire        g_req, g_we;
  wire [22:0] g_addr;
  wire [15:0] g_din;
  reg         g_ack = 0, g_ready = 0;
  reg  [15:0] g_dout = 0;
  reg         frame_tick = 0;
  wire        draw_pg, disp_pg;

  p8x_geom dut(.clk(clk), .rst(rst),
               .sel(sel), .a(a), .wr(wr), .wdata(wdata), .rdata(rdata),
               .gm_own(gm_own), .gm_wr(gm_wr), .gm_a(gm_a),
               .gm_wdata(gm_wdata), .gm_rdata(gm_rdata),
               .g_req(g_req), .g_we(g_we), .g_addr(g_addr), .g_din(g_din),
               .g_ack(g_ack), .g_ready(g_ready), .g_dout(g_dout),
               .frame_tick(frame_tick), .draw_pg(draw_pg), .disp_pg(disp_pg));

  integer errors = 0;

  // ---- SDRAM stub: the list memory, 3-cycle acks --------------------------
  reg [15:0] lmem [0:8191];
  reg [1:0]  glat = 0;
  always @(posedge clk) begin
    g_ack <= 0; g_ready <= 0;
    if (g_req && !g_ack && glat != 3) glat <= glat + 2'd1;
    else if (g_req && glat == 3) begin
      glat <= 0;
      g_ack <= 1;
      if (g_we) lmem[(g_addr - 23'h100000) >> 1] <= g_din;
      else begin g_dout <= lmem[(g_addr - 23'h100000) >> 1]; g_ready <= 1; end
    end
  end

  // ---- gfx stub: capture what the engine draws ----------------------------
  reg [15:0] rx0, ry0, rx1, ry1, rcol;
  reg [3:0]  gbusy = 0;
  reg [15:0] lines_x0 [0:31]; reg [15:0] lines_y0 [0:31];
  reg [15:0] lines_x1 [0:31]; reg [15:0] lines_y1 [0:31];
  reg [15:0] lines_pen [0:31];
  integer    nlines = 0;
  reg [15:0] era_x0, era_y0, era_x1, era_y1, era_pen;
  integer    nera = 0;
  always @(posedge clk) begin
    if (gbusy != 0) gbusy <= gbusy - 4'd1;
    if (gm_own && gm_wr) begin
      case (gm_a)
        4'h0: rx0  <= {8'd0, gm_wdata};
        4'h1: ry0  <= {8'd0, gm_wdata};
        4'h2: rx1  <= {8'd0, gm_wdata};
        4'h3: ry1  <= {8'd0, gm_wdata};
        4'h9: rx0  <= {gm_wdata, rx0[7:0]};
        4'hA: ry0  <= {gm_wdata, ry0[7:0]};
        4'hB: rx1  <= {gm_wdata, rx1[7:0]};
        4'hC: ry1  <= {gm_wdata, ry1[7:0]};
        4'h4: rcol <= {8'd0, gm_wdata};
        4'hD: rcol <= {gm_wdata, rcol[7:0]};
        4'h5: begin
          gbusy <= 4'd6;                       // hold busy: polling is real
          if (gm_wdata == 8'h04) begin         // BOXFILL = the erase
            era_x0 <= rx0; era_y0 <= ry0; era_x1 <= rx1; era_y1 <= ry1;
            era_pen <= rcol; nera = nera + 1;
          end else if (gm_wdata == 8'h02) begin
            lines_x0[nlines] <= rx0; lines_y0[nlines] <= ry0;
            lines_x1[nlines] <= rx1; lines_y1[nlines] <= ry1;
            lines_pen[nlines] <= rcol;
            nlines = nlines + 1;
          end
        end
        default: ;
      endcase
    end
  end
  always @(*) gm_rdata = (gm_a == 4'h6) ? {(gbusy != 0), 7'd0} : 8'hFF;

  // frame_tick every 500 cycles -- slow enough to catch busy-holds
  integer ftc = 0;
  always @(posedge clk) begin
    ftc = ftc + 1;
    frame_tick <= (ftc % 500 == 0);
  end

  // ---- drivers -------------------------------------------------------------
  task wr8(input [3:0] ra, input [7:0] v);
    begin
      @(negedge clk); sel = 1; wr = 1; a = ra; wdata = v;
      @(negedge clk); sel = 0; wr = 0;
    end
  endtask
  task wpar(input [4:0] idx, input [15:0] v);
    begin
      wr8(4'h0, {3'd0, idx});
      wr8(4'h1, v[7:0]);
      wr8(4'hA, v[15:8]);
    end
  endtask
  task up16(input [15:0] v);
    // paced: a real CPU poke is ~60 cycles of instructions apart; even this
    // 6-cycle gap is 10x faster than software can drive GEUP. The 4-deep
    // FIFO absorbs arbitration stalls, not a zero-gap firehose.
    begin
      wr8(4'h2, v[7:0]);  repeat (6) @(negedge clk);
      wr8(4'h2, v[15:8]); repeat (6) @(negedge clk);
    end
  endtask
  task upedge(input [15:0] c, input [15:0] x0,y0,z0,x1,y1,z1);
    // a stage-9 LINE record: type/flags halfword, colour, then the verts
    begin
      up16(16'h0001); up16(c);
      up16(x0); up16(y0); up16(z0); up16(x1); up16(y1); up16(z1);
    end
  endtask
  task wait_idle;
    integer n;
    begin
      n = 0; a = 4'h4; sel = 1;
      while (rdata[7] && n < 200000) begin @(negedge clk); n = n + 1; end
      sel = 0;
      if (n >= 200000) begin $display("FAIL: engine never went idle"); errors = errors + 1; end
    end
  endtask
  task expline(input integer i, input [15:0] pen, input [15:0] x0,y0,x1,y1);
    begin
      if (lines_x0[i] !== x0 || lines_y0[i] !== y0 ||
          lines_x1[i] !== x1 || lines_y1[i] !== y1) begin
        $display("FAIL: line %0d = (%0d,%0d)-(%0d,%0d), want (%0d,%0d)-(%0d,%0d)",
                 i, lines_x0[i], lines_y0[i], lines_x1[i], lines_y1[i], x0,y0,x1,y1);
        errors = errors + 1;
      end
      if (lines_pen[i] !== pen) begin
        $display("FAIL: line %0d pen %04X, want %04X", i, lines_pen[i], pen);
        errors = errors + 1;
      end
    end
  endtask

  initial begin
    repeat (4) @(negedge clk); rst = 0; repeat (2) @(negedge clk);

    // probe
    a = 4'h5; sel = 1; #1;
    if (rdata !== 8'h45) begin $display("FAIL: GEID != 'E'"); errors = errors + 1; end
    sel = 0;

    // window/viewport/focal (identity matrix + t=0 come from reset... but
    // set t explicitly: reset leaves it 0; flags: erase, NO flip for run 1)
    wpar(5'd13, -16'sd120); wpar(5'd14, -16'sd120);
    wpar(5'd15,  16'sd120); wpar(5'd16,  16'sd120);
    wpar(5'd17,  16'sd104); wpar(5'd18,  16'sd0);
    wpar(5'd19,  16'sd375); wpar(5'd20,  16'sd271);
    wpar(5'd12,  16'sd256);
    wpar(5'd21,  16'sd1);

    // upload the 7 identity-set records, each with a DISTINCT colour
    wr8(4'h3, 8'h01);                        // rewind cursor
    upedge(16'hF800, -16'sd80, -16'sd60, 16'sd300,  16'sd80,  16'sd60, 16'sd500);
    upedge(16'h07E0, -16'sd90,  16'sd40, -16'sd30,  16'sd90,  16'sd40, 16'sd600);
    upedge(16'h001F, -16'sd500, 16'sd0,  16'sd260,  16'sd500, 16'sd0,  16'sd260);
    upedge(16'hFFE0,  16'sd0,  -16'sd400, 16'sd300, 16'sd0,   16'sd400, 16'sd300);
    upedge(16'h1234,  16'sd10,  16'sd10, -16'sd50,  16'sd20,  16'sd20, -16'sd90);
    upedge(16'h4321,  16'sd2000, 16'sd2000, 16'sd200, 16'sd3000, 16'sd3000, 16'sd200);
    upedge(16'hFFFF, -16'sd110, -16'sd110, 16'sd280, 16'sd110, 16'sd110, 16'sd700);
    wpar(5'd22, 16'd7);
    wr8(4'h3, 8'h02);                        // RENDER
    wait_idle;
    a = 4'h4; sel = 1; #1;
    if (rdata[0]) begin $display("FAIL: GESTAT err set after run 1"); errors = errors + 1; end
    sel = 0;

    // the erase must be the viewport in pen 0
    if (nera !== 1 || era_pen !== 16'h0000 ||
        era_x0 !== 16'd104 || era_y0 !== 16'd0 ||
        era_x1 !== 16'd375 || era_y1 !== 16'd271) begin
      $display("FAIL: erase box/pen wrong (n=%0d pen=%04X %0d,%0d-%0d,%0d)",
               nera, era_pen, era_x0, era_y0, era_x1, era_y1);
      errors = errors + 1;
    end
    // 5 lines survive of 7 -- from the host replica, verbatim
    if (nlines !== 5) begin
      $display("FAIL: %0d lines drawn, want 5", nlines); errors = errors + 1;
    end
    expline(0, 16'hF800, 16'd162, 16'd194, 16'd284, 16'd102);
    expline(1, 16'h07E0, 16'd104, 16'd29,  16'd282, 16'd117);
    expline(2, 16'h001F, 16'd375, 16'd136, 16'd104, 16'd136);
    expline(3, 16'hFFE0, 16'd239, 16'd0,   16'd239, 16'd271);
    expline(4, 16'hFFFF, 16'd126, 16'd249, 16'd284, 16'd91);

    // no flip requested: pages untouched
    if (draw_pg !== 1'b0 || disp_pg !== 1'b0) begin
      $display("FAIL: flags=1 must not flip"); errors = errors + 1;
    end

    // ---- run 2: the cube frame-0 matrix, 3 edges, WITH flip ---------------
    nlines = 0; nera = 0;
    wpar(5'd0, 16'd240); wpar(5'd1, 16'd0);   wpar(5'd2, 16'd0);
    wpar(5'd3, 16'd0);   wpar(5'd4, 16'd240); wpar(5'd5, 16'd0);
    wpar(5'd6, 16'd0);   wpar(5'd7, 16'd0);   wpar(5'd8, 16'd225);
    wpar(5'd9, 16'd0);   wpar(5'd10, 16'd0);  wpar(5'd11, 16'd400);
    wpar(5'd21, 16'd3);                      // erase + flip
    wr8(4'h3, 8'h01);
    upedge(16'hF800, -16'sd90, -16'sd90, -16'sd90,  16'sd90, -16'sd90, -16'sd90);
    upedge(16'hF800,  16'sd90, -16'sd90, -16'sd90,  16'sd90,  16'sd90, -16'sd90);
    upedge(16'h001F, -16'sd90, -16'sd90, -16'sd90, -16'sd90, -16'sd90,  16'sd90);
    wpar(5'd22, 16'd3);
    wr8(4'h3, 8'h02);                        // RENDER (holds busy to vsync)
    wait_idle;
    if (nlines !== 3) begin
      $display("FAIL: cube run drew %0d lines, want 3", nlines); errors = errors + 1;
    end
    expline(0, 16'hF800, 16'd162, 16'd213, 16'd315, 16'd213);
    expline(1, 16'hF800, 16'd315, 16'd213, 16'd315, 16'd60);
    expline(2, 16'h001F, 16'd162, 16'd213, 16'd188, 16'd187);
    // the flip rule: display <- draw (0), draw <- other (1)
    if (disp_pg !== 1'b0 || draw_pg !== 1'b1) begin
      $display("FAIL: flip pages disp=%b draw=%b, want 0/1", disp_pg, draw_pg);
      errors = errors + 1;
    end

    // ---- manual FLIP -------------------------------------------------------
    wr8(4'h3, 8'h03);
    wait_idle;
    if (disp_pg !== 1'b1 || draw_pg !== 1'b0) begin
      $display("FAIL: manual flip disp=%b draw=%b, want 1/0", disp_pg, draw_pg);
      errors = errors + 1;
    end

    // ---- PGSYNC: draw rejoins display, instantly ---------------------------
    wr8(4'h3, 8'h04);
    @(negedge clk);
    if (disp_pg !== 1'b1 || draw_pg !== 1'b1) begin
      $display("FAIL: PGSYNC disp=%b draw=%b, want 1/1", disp_pg, draw_pg);
      errors = errors + 1;
    end

    if (errors == 0) $display("TB-GEOM: PASS (erase, pen, 5+3 lines vs host replica, clip/drop/reject, flip + PGSYNC rules)");
    else $display("TB-GEOM: %0d FAILURES", errors);
    $finish;
  end
endmodule
