#!/usr/bin/env python3
"""memaddr.py - resolve a memory-map SYMBOL to its address, from the single
source (generators/memmap.py, itself generated by gen_memmap.py).

The point: shell test scripts that poke the monitor by literal hex address
(`E 60AF` for GCONEN) go silently stale when the map moves -- exactly the
bug that left the whole GL test suite comparing against the wrong byte after
GCONEN slid from $60AF to $1FAF on the 6K-ROM flag-day. Resolving the address
here instead means a map move can never leave a test poking dead memory.

Usage:
  python3 tools/memaddr.py GCONEN          -> 1FAF        (bare hex, no $/0x)
  python3 tools/memaddr.py GCONEN --0x     -> 0x1FAF
  python3 tools/memaddr.py GCONEN GTSUSP   -> 1FAF 1FA7   (space-separated)

Shell:
  GCONEN=$(python3 $ROOT/tools/memaddr.py GCONEN)
  printf "E ${GCONEN}\r00.G 014E\r..."
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "generators"))
import memmap                                    # the generated map module


def main(argv):
    pref = ""
    names = []
    for a in argv:
        if a == "--0x":
            pref = "0x"
        elif a == "--dollar":
            pref = "$"
        else:
            names.append(a)
    if not names:
        sys.exit("usage: memaddr.py SYMBOL [SYMBOL...] [--0x|--dollar]")
    out = []
    for n in names:
        v = getattr(memmap, n, None)
        if not isinstance(v, int):
            sys.exit("memaddr.py: no such map symbol: %s" % n)
        out.append("%s%X" % (pref, v))
    print(" ".join(out))


if __name__ == "__main__":
    main(sys.argv[1:])
