# Author: Claude (Anthropic) for Ken Rother, 2026
"""Copy the P8X documents the website uses into stage/, keeping each file's repository path, so the links between
them keep working. Anything not copied is linked to GitHub by hooks.py. The source is this repository's working
tree, read only: nothing here writes to it.

Generated on top of the copies: the home page (home.md here), the "Working on the code" page (the repository README),
a memory-map page (from generators/memmap.py), one page per manual page (os/man/*), and the board renders (resized,
and shown at the top of each board's page, plus the assembled-machine renders)."""
import glob, os, re, shutil
from hooks import BRANCH, GH                       # the one place the GitHub branch is named

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # the repository this folder is in
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "stage")
BOARDS = ["control-card", "regbank-card", "alu-card", "memory-card", "io-card", "cf-card", "ps2-card", "backplane",
          "bustest-card"]
FILES = ["BACKLOG.md", "GLOSSARY.md", "hardware/README.md", "hardware/KICAD-BOARDS.md", "hardware/RECONCILIATION.md",
         "hardware/assembly/README.md", "hardware/reference/README.md", "microcode/README.md", "firmware/README.md",
         "rom/README.md", "assembler/README.md", "compiler/README.md", "basic/README.md", "basic/p8x-basic-guide.md",
         "apps/README.md", "emulator/README.md", "tools/README.md", "tools/gatesim/README.md", "generators/README.md",
         "os/README.md", "os/commands/README.md", "os/commands-asm/README.md", "os/man/README.md"]
GLOBS = ["docs/*.md", "fpga/**/*.md"] + ["hardware/%s/*.md" % b for b in BOARDS]
# never on the site: Claude's memory mirror, frozen / parked / deprecated trees, logs, agent notes, the review dump
SKIP = re.compile(r"(^|/)(docs/memory|eagle-deprecated|deprecated|parked|logs)(/|$)|(^|/)(CLAUDE|CODE_REVIEW)\.md$")

# [[name]] (or [[name|text]]) is a wiki-link into the memory notes (docs/memory), which the site leaves out:
# a staged document shows just the name (or the text), as plain text, instead of the literal brackets
WIKILINK = re.compile(r"\[\[([^\[\]|\n]+)(?:\|([^\[\]\n]+))?\]\]")


def plain_wikilinks(path):
    text = open(path, encoding="utf-8").read()
    new = WIKILINK.sub(lambda m: (m.group(2) or m.group(1)).strip(), text)
    if new != text: open(path, "w", encoding="utf-8").write(new)
    return text.count("[[") - new.count("[[")


shutil.rmtree(OUT, ignore_errors=True)
n = 0
wikilinks = 0
paths = set(FILES)
for g in GLOBS:
    paths |= {os.path.relpath(p, REPO) for p in glob.glob(os.path.join(REPO, g), recursive=True)}
for rel in sorted(paths):
    src = os.path.join(REPO, rel)
    if SKIP.search(rel) or not os.path.isfile(src): continue
    dst = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst); n += 1
    if dst.endswith(".md"): wikilinks += plain_wikilinks(dst)
# the visitor home page (home.md here) is the site's index; the repository README becomes the "Working on the code"
# page (links to README.md from other documents are pointed at it by hooks.py)
shutil.copy2(os.path.join(HERE, "home.md"), os.path.join(OUT, "index.md")); n += 1
# the home page's lead picture: a collage of the assembled-machine renders and the memory card (website/p8x-collage.jpg,
# made from hardware/assembly/*.png and hardware/memory-card/kicad/*-render-3d.png; replace it with photos once the
# boards are built)
os.makedirs(os.path.join(OUT, "media"), exist_ok=True)
shutil.copy2(os.path.join(HERE, "p8x-collage.jpg"), os.path.join(OUT, "media", "p8x-collage.jpg")); n += 1
shutil.copy2(os.path.join(REPO, "README.md"), os.path.join(OUT, "repository.md")); n += 1
for page in ("index.md", "repository.md"): wikilinks += plain_wikilinks(os.path.join(OUT, page))
print("wiki-links made plain: %d" % wikilinks)


def write(rel, lines):
    path = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w", encoding="utf-8").write("\n".join(lines).rstrip() + "\n")


def cell(s):
    return s.replace("|", "\\|")


# --- the memory map, one table per section of generators/memmap.py (generated by gen_memmap.py, the single source)
lines = ["# Memory map", "",
         "Every data address P8X software uses, as `generators/gen_memmap.py` defines it: memory regions, I/O ports and "
         "the scratch areas of the BIOS, the OS and the commands. The same generator writes `memmap.inc` for the "
         "assembler and `memmap.h` for C, and the [printable memory map](p8x-memory-map.pdf) is generated from it too. "
         "This page is built from its "
         "Python output, [`generators/memmap.py`](../generators/memmap.py), so it cannot disagree with it.", "",
         "In short: ROM `$0000-$17FF` (6 KB, the monitor and BIOS), RAM `$1800-$FEFF`, I/O `$FF00-$FFFF`. The OS loads "
         "at `$2000`; programs run from `$5900`.", ""]
tables, current = {}, None                              # a section title that comes back again continues its table
for line in open(os.path.join(REPO, "generators/memmap.py"), encoding="utf-8"):
    line = line.rstrip("\n")
    m = re.match(r"^# (.+)$", line)
    if m and "GENERATED" not in line:
        current = m.group(1)[0].upper() + m.group(1)[1:]
        tables.setdefault(current, [])
        continue
    m = re.match(r"^([A-Z_][A-Z0-9_]*)\s*=\s*([^#]+?)\s*(?:#\s*(.*))?$", line)
    if m and current:
        val = m.group(2)
        if re.fullmatch(r"0x[0-9A-Fa-f]+", val): val = "$" + val[2:].upper()
        tables[current].append("| `%s` | `%s` | %s |" % (m.group(1), cell(val), cell(m.group(3) or "")))
for title, rows in tables.items():
    lines += ["## " + title, "", "| Name | Value | Notes |", "|---|---|---|"] + rows + [""]
write("docs/memory-map.md", lines); n += 1
sections = len(tables)
print("memory map: %d sections" % sections)

# --- one page per manual page (os/man/NAME, plain text): the NAME line as the heading, the page as `man NAME` prints
# it on the machine, and its SEE ALSO entries as links; plus an index of them all
man_dir = os.path.join(REPO, "os/man")
names = sorted(f for f in os.listdir(man_dir) if f != "README.md" and os.path.isfile(os.path.join(man_dir, f)))
readme = open(os.path.join(man_dir, "README.md"), encoding="utf-8").read()
m = re.search(r"LIBRARIES that commands splice in \(([^)]*)\)", readme)
libraries = set(re.findall(r"`(\w+)`", m.group(1))) if m else set()
entries = {}
for name in names:
    text = open(os.path.join(man_dir, name), encoding="utf-8").read().rstrip()
    body = text.splitlines()
    summary = ""
    if body and body[0].strip() == "NAME" and len(body) > 1:
        summary = body[1].strip()
        summary = summary.split(" - ", 1)[1] if " - " in summary else summary
    entries[name] = summary
    see = []
    if "SEE ALSO" in body:
        for l in body[body.index("SEE ALSO") + 1:]:
            if l and not l.startswith(" "): break
            see += [w.strip() for w in re.split(r"[,\s]+", l) if w.strip()]
    fence = "`" * max(3, max((len(r) for r in re.findall(r"`+", text)), default=0) + 1)
    page = ["# %s" % name, ""]
    if summary: page += ["*%s*" % summary, ""]
    page += [fence + "text", text, fence, ""]
    links = ["[%s](%s.md)" % (w, w) for w in see if w in names and w != name]
    if links: page += ["See also: " + ", ".join(links), ""]
    page += ["*The text of `man %s` on P8X ([`os/man/%s`](<%s/blob/%s/os/man/%s>) in the repository).* "
             "[All commands](index.md)" % (name, name, GH, BRANCH, name)]
    write("commands/%s.md" % name, page); n += 1
idx = ["# Commands", "",
       "The manual pages that ship on the P8X disk in `/man`, one page each: the same text `man NAME` prints on the "
       "machine. They cover the shell built-ins and the `/bin` programs, and the shared libraries a C or assembler "
       "command splices in with `//#use` (`;#use` in assembler). [About the manual pages](../os/man/README.md).", "",
       "## Commands and programs", "", "| Command | What it does |", "|---|---|"]
idx += ["| [%s](%s.md) | %s |" % (k, k, cell(entries[k])) for k in names if k not in libraries]
idx += ["", "## Libraries (`//#use`)", "", "| Library | What it provides |", "|---|---|"]
idx += ["| [%s](%s.md) | %s |" % (k, k, cell(entries[k])) for k in names if k in libraries]
write("commands/index.md", idx); n += 1
print("manual pages: %d (%d libraries)" % (len(names), len([k for k in names if k in libraries])))

# --- board renders (KiCad, hardware/BOARD/kicad/*-render-{3d,top}.png; 1768 px, transparent background), resized for
# the web, and the 3D view shown at the top of each board's page with a link to the top view
from PIL import Image
BOARD_PAGE = {"backplane": "p8x-backplane-design.md", "bustest-card": "p8x-bustest-card-design.md"}
renders = 0
for b in BOARDS:
    for view in ("3d", "top"):
        src = os.path.join(REPO, "hardware", b, "kicad", "p8x-%s-render-%s.png" % (b, view))
        if not os.path.exists(src): continue
        im = Image.open(src)
        im.thumbnail((1000, 1000))
        dst = os.path.join(OUT, "hardware", b, "kicad", os.path.basename(src))
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        im.quantize(256, method=Image.Quantize.FASTOCTREE).save(dst, optimize=True)
        renders += 1; n += 1
    page = os.path.join(OUT, "hardware", b, BOARD_PAGE.get(b, "README.md"))
    if os.path.exists(page) and os.path.exists(os.path.join(OUT, "hardware", b, "kicad", "p8x-%s-render-3d.png" % b)):
        md = open(page, encoding="utf-8").read().split("\n")
        h1 = next((i for i, l in enumerate(md) if l.startswith("# ")), -1)
        figure = ["", "![%s, KiCad 3D render](kicad/p8x-%s-render-3d.png)" % (md[h1][2:].strip(), b), "",
                  "*The board as routed in KiCad (3D render; [top view](kicad/p8x-%s-render-top.png)).*" % b]
        md[h1 + 1:h1 + 1] = figure
        open(page, "w", encoding="utf-8").write("\n".join(md))
# the assembled-machine renders (hardware/assembly/*.png, 2400 px, from generators/render_assembly.py), resized for
# the web; their gradient background bands at 256 colours, so they are dithered. hardware/assembly/README.md shows them
for src in sorted(glob.glob(os.path.join(REPO, "hardware", "assembly", "*.png"))):
    im = Image.open(src).convert("RGB")
    im.thumbnail((1400, 1400))
    dst = os.path.join(OUT, "hardware", "assembly", os.path.basename(src))
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    pal = im.quantize(256, method=Image.Quantize.FASTOCTREE)
    im.quantize(palette=pal, dither=Image.Dither.FLOYDSTEINBERG).save(dst, optimize=True)
    renders += 1; n += 1
print("board renders: %d" % renders)
print("staged %d files" % n)
